### ISSUE TITLE
Minor suggestion: either remove the line indicator for tabs or remove the background

### ISSUE THREAD

**Issue by itsWindows11** [bkaankose/Wino-Mail#1]
![image](https://user-images.githubusercontent.com/81253203/134501947-a4f4ef96-1417-4aa9-82d4-bba81296b37f.png)

I haven't tested the app yet but this is a suggestion, it looks inconsistent this way from my point of view, you should remove one of the following:

- The line indicator at the bottom
- The background

**Comment by binamracode** [comment]
![image](https://user-images.githubusercontent.com/61900781/134506149-a803c455-6731-46bb-b308-34cba8b43832.png)
This will look better in my opinion

**Comment by bkaankose** [comment]
I would go with the background removal as well. Better to keep the indicator since it's animated.

**Comment by itsWindows11** [comment]
> ![image](https://user-images.githubusercontent.com/61900781/134506149-a803c455-6731-46bb-b308-34cba8b43832.png)
> This will look better in my opinion

I agree

**Comment by bkaankose** [comment]
Removed the background color for selected tab in the new Preview release.

![image](https://user-images.githubusercontent.com/12009960/219344089-fd1d4760-58d7-4386-b14b-00826c0fa277.png)
