### ISSUE TITLE
Please Add Chinese Simplified language in Crowdin, Thanks

### ISSUE THREAD

**Issue by WebPavel** [bkaankose/Wino-Mail#102]
Please Add Chinese Simplified language in Crowdin, Thanks a lot.  
After that, I wish to translate this excellent app and present it to more Chinese users.  
My Crowdin account username is lewPau.  
Sincerely

**Comment by bkaankose** [comment]
Chinese Simplified is added in Crowdin project.

Thank you! @WebPavel
