### ISSUE TITLE
Scrollbars difficult to view in dark mode

### ISSUE THREAD

**Issue by edge261** [bkaankose/Wino-Mail#106]
**Describe the bug**
Although the scrollbars match Windows 11 principles, the color scheme in dark mode does not match the standard ones, so they're difficult to view. Screenshots attached below.

Also, I think that to maximize the space available to the email, to match the web expected behavior and give better aesthetic, the "overlay scrollbars" flag should be enabled in WebView2.

**Expected behavior**
This is how the scrollbars should look like: (using Edge as reference)

Scroll active:
![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/b7f0c0e3-b44b-490f-b205-d2ac81dcaf87)

Mouse hovered:
![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/bb740dc1-762d-459e-b366-5d7017af1f7f)

**Screenshots**
This is the current behavior:

![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/88b05f67-3222-4698-b220-ed646cc085d1)

**Comment by edge261** [comment]
wondering if this issue will be fixed...

**Comment by bkaankose** [comment]
> wondering if this issue will be fixed...

Merged @Tiktack PR. It'll be fixed for the next release.

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Closing the issue since it's already fixed in the release.
