### ISSUE TITLE
There is no trash-folder on Gmail-IMAP accounts. Folders are not translated

### ISSUE THREAD

**Issue by sbo76** [bkaankose/Wino-Mail#107]
**Describe the bug**
I don't have a trash folder (IMAP) on my two GMAIL accounts. In addition, the folder names are not translated into German

![image](https://github.com/bkaankose/Wino-Mail/assets/157953359/1311c3d9-2f87-4756-9981-4b9a473cfc95)

**Comment by bkaankose** [comment]
Wino has different behaviors for all 3 account types. If you see Gmail logo for your account it means you are using Gmail API synchronizer. I found this information which may help you with the Trash folder visibility

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/1f1d864e-6db7-433c-a325-3956b00ac8f3)

Can you enable it and try again?

For the translated folders Wino does not do anything special with IMAP synchronization. Folders are named like that in your mail server.

**Comment by sbo76** [comment]
Thank you! Works now. It's not a bug.
