### ISSUE TITLE
Cannot copy content from e-mails

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#11]
This prevents above all to copy security codes sent by e-mail

**Comment by MarcAnt01** [comment]
@bkaankose has something been done in the last update? It seems to work now

**Comment by bkaankose** [comment]
Nothing that I am aware of :/ There should be nothing that blocks the input there. Glad that it's been resolved somehow :) I will close this issue for now. Feel free to re-open is you encounter the issue again.
