### ISSUE TITLE
Validation error sending mail

### ISSUE THREAD

**Issue by whcchief** [bkaankose/Wino-Mail#110]
When attempting to send an email to a billing department at a company, the message could not be sent with the error:

"Validation failed mail does not contain any recipients"
Of course, I double checked and it was entered.

I am using a gmail account. I am using 1.6.12 from the MS store.

There was no other information to provide.

**Comment by bkaankose** [comment]
You need to tap "enter" to add mail as a recipient. 

If it looks like this it won't work
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/bd314262-4f0d-4008-bb62-25b24332b06f)

but this will work
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/6fa0434c-2bf2-478e-a8fa-693c0ea1ec79)

**Comment by whcchief** [comment]
I see, I am sure I tried that, perhaps adding tab button to assist with this? Thanks for replying either way.

**Comment by bkaankose** [comment]
Next version will automatically add any valid mail addresses on unfocus on that entry place. You can close the issue if using enter works for you. If not could you provide which address you use?

Thanks.
