### ISSUE TITLE
[Proposal] Change behaviour of account tiles

### ISSUE THREAD

**Issue by clragon** [bkaankose/Wino-Mail#112]
**Describe the solution you'd like**

In Windows Mail, clicking on an account tile immediately allowed seeing the Emails.

Screenshot from Windows Mail:
![4K1zEOwEYD](https://github.com/bkaankose/Wino-Mail/assets/11785085/cf0ab5c1-2978-42a9-9045-f1e1bd4d7e5f)

Since I have many email accounts, this was very useful because I needed to quickly switch between them.

This is not really possible in Wino, where I have to un-expand the Tile first before being able to click the Inbox.
My emails have so many subentries that I can not see all of them at once when they are all expanded.
This leads to a significant slow down in checking all my accounts.

I am not entirely sure how this could be solved. Maybe clicking on a tile would switch to its inbox _and_ expand it?
However, this would still need me to un-expand it everytime. 
The tile could also be split with the default surface opening the inbox, and the arrow at the end expanding it.
We could also copy the design from Windows Mail though I assume there is a reason that was not done.

**Is your proposal implemented in Windows Mail?**

Yes, Windows Mail allows me to very quickly switch between the inboxes of all my accounts.
Wino has chosen a different design from Windows Mail, so without changing the account sidebar significantly, we cant directly copy their solution.

**Comment by bkaankose** [comment]
Account navigation system is reworked for the next public release, but you can give it a try in current beta version.

You can download the current beta version (**1.7.0**) here

https://github.com/bkaankose/Wino-Mail/releases/tag/beta

If you experience certification issues you can follow the guide below
https://learn.microsoft.com/en-us/windows/application-management/sideload-apps-in-windows

Marking the issue as fixed for now. I'll close the issue once it is released to Store.

**Comment by clragon** [comment]
Very exciting, I have given it a whirl and this is exactly what I wished for. Thank you!
