### ISSUE TITLE
[Proposal] Dark Mode enhancements

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#113]
**Describe the solution you'd like**
When using dark mode it's hard to distinguish which mails are unread and which not. I know the sender's name is getting bold and title gets accent color but maybe some left border indicator would help? Or at least some different item background (just more obvious than standard current item highlight).

**Is your proposal implemented in Windows Mail?**
Yes, it's easier to distinguish unreaded items in Windows Mail and it has indicator on left border for them.

**Comment by Tiktack** [comment]
Please no. Current implementation very to understand and it's not cluttering UI.

**Comment by Tiktack** [comment]
Closing as duplicate. We are tracking the issue on #198
