### ISSUE TITLE
[Proposal]Minimize/Close to Tray

### ISSUE THREAD

**Issue by errende** [bkaankose/Wino-Mail#115]
It would be nice to have a toggle available like with apps such as discord or qbittorrent. 
Hitting the Square or X button to hide Wino Mail in the system tray while still getting notifications updates.

**Comment by bkaankose** [comment]
Wino Mail is a UWP application. UWP apps can't minimize themselves to system tray without asking for full thrust capability, which will ask users to approve a message that if Wino can use all their system resources. This is something I want to avoid for now.

Another option to switch from UWP to WinApp SDK. I don't have plans to rework Wino's tech stack into WinApp SDK anytime soon as long as they don't leverage DWM fully. It's visibly slow compared to UWP.

For now stability of background tasks is more important for background notifications. If there'll be demand later on from the user base we can discuss this decision together again.
