### ISSUE TITLE
[Proposal] Add 24 time format

### ISSUE THREAD

**Issue by thesergeev** [bkaankose/Wino-Mail#120]
**Describe the solution you'd like**
Add please option to choose time format of mail arrival.

**Is your proposal implemented in Windows Mail?**
No. Now I can see only 12 time format in my inbox.  
I can't find this option. I think the best place for this option is in Personalization tab.

**Additional context**
![Screenshot_Inbox ‎- Wino Mail_2024-02-25_15 11 10](https://github.com/bkaankose/Wino-Mail/assets/1877740/f1e0f8bb-cf10-42e9-a43b-59709de91c51)

**Comment by bkaankose** [comment]
This has been discussed previously on some other issues and the approach you mentioned was approved, but it was never implemented so far.

I will make sure that it gets included in the next release. Regardless of the UI culture, people should be able to change the time format of their choices.

**Comment by MichalVasut** [comment]
@bkaankose  you should also be able to get culture specific format

https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#time-formats

I'm not sure if the app is using .NET, only guessing...

**Comment by bkaankose** [comment]
Beta version has the following option under settings

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/94e478e9-3b26-4940-b5e3-51f67b40454f)

This definitely can be improved with different globalization options later on, but I believe this is a good start for now.

You can try to install the beta version here
https://github.com/bkaankose/Wino-Mail/releases/tag/beta

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Closing the issue since it's already fixed in the release.
