### ISSUE TITLE
To-Address doesnt get saved in a draft

### ISSUE THREAD

**Issue by weber-man** [bkaankose/Wino-Mail#121]
**Describe the bug**
When writing an email as a draft and then closing the application or clicking on another email, so the draft gets closed, then the receiver Email doesn't get saved. Same with Cc and Bcc.

**Expected behavior**
When Opening the Draft again the Receiver Email (the To: , Cc: , Bcc:) fields should be populated with the email addresses i put in earlier

**Comment by bkaankose** [comment]
Draft system is completely reworked for the next release. We need to reproduce this once it's released FYI.

**Comment by bkaankose** [comment]
Can you try to reproduce this issue in the beta release?

https://github.com/bkaankose/Wino-Mail/releases/tag/beta

**Comment by weber-man** [comment]
Couldn't Reproduce it on the new beta Version.
Seems fixed now.
Great work 👍
