### ISSUE TITLE
[Bug] "Mail doesn't contain any recipients" 

### ISSUE THREAD

**Issue by willme1** [bkaankose/Wino-Mail#122]
**Describe the bug**
Drafts cannot be submitted even though a recipient is specified.

**Expected behavior**
As soon as there is any valid email adress in the field, sending should be possible

**Screenshots**
![27-02-2024_07-07-58](https://github.com/bkaankose/Wino-Mail/assets/59962605/de71f0a0-4b4c-49a1-8356-0ce8be6d6def)

**Additional context**
Installation was quick and easy. One mail account (provider "mail.de")  was automatically installed. 
IMAP synch with many subfolders was flawless.

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Recipients automatically will be added if they are valid e-mail addresses when unfocused from the textbox or clicked enter.

Closing the issue since it's already fixed in the release.
