### ISSUE TITLE
Denied Background Execution

### ISSUE THREAD

**Issue by Kirshi912** [bkaankose/Wino-Mail#127]
I don't know whether you know of it, if it have real effect, or something with security setting which i not aware. But that message would appear whenever i open the app, seems like notification really appear only when the app opened. 
Btw this is my first time using this app, and i get it from ms store. 

Win10 home. 
23H2
22631.3235

<img width="563" alt="bu" src="https://github.com/bkaankose/Wino-Mail/assets/130754914/e87d4687-f3bd-46c4-8365-b588e6e85dbd">

**Comment by mreed4** [comment]
Here as well for this issue. I've applied some tweaks to the system before installing Wino.

Win 11 Pro
23H2
22631.3296

**Comment by bkaankose** [comment]
This effort is being tracked on #270 going forward.

Closing as duplicate.
