### ISSUE TITLE
Error background apps

### ISSUE THREAD

**Issue by nguyenphuong10102003** [bkaankose/Wino-Mail#129]
When starting the computer and not opening the application, the application still runs in the background and sends notifications normally. But when I open the app, view my email and X (Close) app, it no longer works in the background and no more notifications appear.
If possible, I want the application to still work in the background and send notifications even after closing the app (without minimizing the icon to the system tray).
When starting the computer and not opening the app
![image](https://github.com/bkaankose/Wino-Mail/assets/76480763/16e97174-0530-46af-9eda-b4ff1c65b206)
When I open the app and then close it
![image](https://github.com/bkaankose/Wino-Mail/assets/76480763/146ed45e-a790-40fa-8bc3-84a841568e6b)

**Comment by bkaankose** [comment]
This issue is tracked here now #270 

Closing as duplicate.
