### ISSUE TITLE
Add Yahoo Mail account

### ISSUE THREAD

**Issue by nguyenphuong10102003** [bkaankose/Wino-Mail#130]
I would like to use Yahoo Mail. Could you please include the option to add Yahoo mail to the Manage account section?

**Comment by bkaankose** [comment]
Yahoo Mail doesn't expose proper API for developers. Therefore, it's only available via IMAP setup in Wino. For that you must use app specific password to authenticate instead of your Yahoo password.

Please check the following guide from Yahoo.
https://help.yahoo.com/kb/SLN15241.html
