### ISSUE TITLE
[Bug] Web Authentication Broker (WAB) authentication failed

### ISSUE THREAD

**Issue by Marx666** [bkaankose/Wino-Mail#131]
When I try to add my outlook account, It always says Web Authentication Broker (WAB) authentication failed. Is there a way to solve this problem or I should wait for an update?
![screenshot-1709802522198](https://github.com/bkaankose/Wino-Mail/assets/13168369/f0ca1b6e-2e72-4637-9045-ff2d3ddf2f43)

**Comment by bkaankose** [comment]
WAB is replaced with WAM broker in beta version. You can give it a try. This is an old issue and probably some external sources caused WAB to not work.

Closing the issue for now.
