### ISSUE TITLE
An Arm64 version is highly needed, the Arm32 version is unusable

### ISSUE THREAD

**Issue by Viruslav** [bkaankose/Wino-Mail#132]
This should have been a feature request but there is also a buggy behavior.

Microsoft already deprecated Arm32 on Windows 11 and removed some functionality (e.g. video codecs). They will drop Arm32 support entirely in the future.

Currently the app displays only the mail titles but not their contents and I suspect it's because of the limited Arm32 support in Windows. The app is unusable in this state.

Also the app crashes after trying to reply to an email and on other actions as well.

**Comment by bkaankose** [comment]
I gave it a try yesterday but building ARM64 never finished unfortunately. I need to diagnose the underlying issue. So this might take some time unfortunately.

**Comment by Viruslav** [comment]
Thanks, I'll be waiting!

**Comment by bkaankose** [comment]
1.8.x versions include ARM64 builds and ARM32 is deprecated going forward. Marking it fixed and will close the issue once beta version goes Store next week.

**Comment by Viruslav** [comment]
Thank you very much!

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
