### ISSUE TITLE
[Bug] Wino Mail Crashes When Reading Some Emails

### ISSUE THREAD

**Issue by RooRay** [bkaankose/Wino-Mail#133]
I'm aware that the title isn't especially helpful but since I can't really narrow down this issue I'm hoping the extra details below can assist.

**Describe the bug**

When opening a Hostelling Scotland membership email I received on Wino Mail with an attached PDF, Wino Mail attempts to open it but then crashes. The email and its attached PDF open fine on the main Outlook clients. Unfortunately I can't share the email itself publicly since it is full of personal information but I may be able to do so privately.

**Expected behaviour**

Wino Mail opens the email and its PDF successfully or just errors instead of full on crashing.

**Screenshots**

Here is a GIF showcasing the issue:

![A GIF showcasing the issue](https://github.com/bkaankose/Wino-Mail/assets/86845749/dc510fb3-c393-49a2-930e-f18d6c3d9e75)

**Additional context**

Wino Mail generated this log file: [WinoDiagnostics.log](https://github.com/bkaankose/Wino-Mail/files/14594005/WinoDiagnostics.log)

**Comment by bkaankose** [comment]
@RooRay could you give it a try with [the beta release](https://github.com/bkaankose/Wino-Mail?tab=readme-ov-file#beta-releases)?

I had some improvements on this area which is not released to Store yet.

**Comment by bkaankose** [comment]
This issue should be fixed in the latest version 1.9.0. Please re-open if you still experience it.
