### ISSUE TITLE
[Proposal] Faster showing of list with already loaded mails

### ISSUE THREAD

**Issue by MichalVasut** [bkaankose/Wino-Mail#136]
**Describe the solution you'd like**

Every time I switch from view to view (Inbox -> folder, folder -> Inbox, folder -> folder, ...), the panel with the list of mails is loaded every time. I would expect to load it for the first time in session (usually when not synced at all or after session start - starting Wino, to load it to the memory).

It's hard to guess how it works internally, but I would guess it's loading from somewhere (mail server or internal DB 🤔 ), isn't it possible to leave some items (at least those "above the fold" = visible without scrolling) in the memory and load rest if needed?

**Is your proposal implemented in Windows Mail?**

Not sure - they forcefully switched to Outlook, but it was faster.

**Comment by bkaankose** [comment]
The way Wino works right now is better. You switch to something else, data that is irrelevant to your folder is cleaned up and new one is loaded from a local SQLite database.

What you propose will increase the memory usage, harder cache management (there is no cache management in Wino, not needed anyways) and can break background sync behavior.

Basically not worth it. Loading up data is pretty fast already.

**Comment by bkaankose** [comment]
> You are right, I've found the sqlite DB file and testes querying it directy, e.g. like
> 
> ```sql
> select mc.* from MailCopy mc 
> join MailCopyAssignment mca on mc.Id=mca.MailCopyId
> join MailItemFolder mif on mif.Id=mca.FolderId
> where mif.RemoteFolderId = "Gitlab";
> ```
> 
> which is fast enough
> 
> ```
> Execution finished without errors.
> Result: 1024 rows returned in 17ms
> ```
> 
> But look how long it takes in the app...
> 
> ![test-loading](https://private-user-images.githubusercontent.com/20949562/315318168-f8385cda-df34-4265-987f-84a894e4aa0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjk5ODksIm5iZiI6MTcxMTAyOTY4OSwicGF0aCI6Ii8yMDk0OTU2Mi8zMTUzMTgxNjgtZjgzODVjZGEtZGYzNC00MjY1LTk4N2YtODRhODk0ZTRhYTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTdkNmRkZGY0ZTdlODlmZGExNGQ4NTM3NGRhMjM0ZTYzMTNjN2U2MTgzNjM5MDMyOGViNzQ1ZTQzNGZhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbtkHiYM16zwTl-V0CcA5gPhqVWRBBbnglQ3KPbqb3s) [ ![test-loading](https://private-user-images.githubusercontent.com/20949562/315318168-f8385cda-df34-4265-987f-84a894e4aa0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjk5ODksIm5iZiI6MTcxMTAyOTY4OSwicGF0aCI6Ii8yMDk0OTU2Mi8zMTUzMTgxNjgtZjgzODVjZGEtZGYzNC00MjY1LTk4N2YtODRhODk0ZTRhYTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTdkNmRkZGY0ZTdlODlmZGExNGQ4NTM3NGRhMjM0ZTYzMTNjN2U2MTgzNjM5MDMyOGViNzQ1ZTQzNGZhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbtkHiYM16zwTl-V0CcA5gPhqVWRBBbnglQ3KPbqb3s) ](https://private-user-images.githubusercontent.com/20949562/315318168-f8385cda-df34-4265-987f-84a894e4aa0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjk5ODksIm5iZiI6MTcxMTAyOTY4OSwicGF0aCI6Ii8yMDk0OTU2Mi8zMTUzMTgxNjgtZjgzODVjZGEtZGYzNC00MjY1LTk4N2YtODRhODk0ZTRhYTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTdkNmRkZGY0ZTdlODlmZGExNGQ4NTM3NGRhMjM0ZTYzMTNjN2U2MTgzNjM5MDMyOGViNzQ1ZTQzNGZhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbtkHiYM16zwTl-V0CcA5gPhqVWRBBbnglQ3KPbqb3s) [ ](https://private-user-images.githubusercontent.com/20949562/315318168-f8385cda-df34-4265-987f-84a894e4aa0c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjk5ODksIm5iZiI6MTcxMTAyOTY4OSwicGF0aCI6Ii8yMDk0OTU2Mi8zMTUzMTgxNjgtZjgzODVjZGEtZGYzNC00MjY1LTk4N2YtODRhODk0ZTRhYTBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTdkNmRkZGY0ZTdlODlmZGExNGQ4NTM3NGRhMjM0ZTYzMTNjN2U2MTgzNjM5MDMyOGViNzQ1ZTQzNGZhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbtkHiYM16zwTl-V0CcA5gPhqVWRBBbnglQ3KPbqb3s)

Delay doesn't come from running query. There are other actions performed in memory for each of those items like creating threads. To create threads you can't rely on just queried data because you will need mails from Draft or Sent folders to be merged as well to create a conversation thread :) Threading algorithm used in Wino is similar to what [jwz explains in his article](https://www.jwz.org/doc/threading.html). Not the exact implementation but similar one. There is also threading algorithm baked in Mailkit library Wino use, but the data model is not fully compatible with that one so it's not used.

Preparing threads is one aspect of things. There are many more to add on top of this like displaying those threads in filtered/sorted observable collection. Each of these things contribute to the delay.

Infinite scroll is implemented in the next version which I hope it'll reduce this delay by loading less items at first but iteratively as users scroll.
 
Nevertheless, if you are willing to contribute you can take a look at the code when the app goes open source. However, caching items per-folder to speed things up is not something I will merge into codebase 💯

**Comment by MichalVasut** [comment]
> for each of those items like creating threads

Threads don't need to be visible immediately, but lazy loaded when shown - this is also (if I remember correctly) behavior of original Windows mail, but I'm not sure if that component is list or it also allows "accordion" (items can be expanded and contains other sublist - in this case thread)

> displaying those threads in filtered/sorted observable collection

Some filtering / sorting can be done on db level and don't bother with it on app level, where (in DB) you can also add some indexes (there aren't any - if the viewer loaded that file correctly). 

> Infinite scroll is implemented in the next version

Great to hear that!

> Nevertheless, if you are willing to contribute you can take a look at the code when the app goes open source.  

I'm definitely looking for taking look into it, but with the contribution, it'll be worse - I'm python web developer and don't really like .NET 😅 - everything is wrong there 🤣. 

> However, caching items per-folder to speed things up is not something I will merge into codebase 💯 

Don't worry, when the DB isn't issue, there is no need for cache. Moreover the Sqllite serves kind of as a cache itself.
