### ISSUE TITLE
[Bug] Wrong processing of cyrillic symbols when sending emails

### ISSUE THREAD

**Issue by shoker537** [bkaankose/Wino-Mail#140]
**Describe the bug**
When writing and sending an email using Wino and the text has cyrillic symbols, the email service receives the text in wrong encoding which breaks the text (shows random symbols).

**Expected behavior**
Using cyrillic symbols in emails does not break the text

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/17161332/ba44a98e-56fe-4f43-a7aa-6d7ca2fcd6a2)

**Additional context**
It only breaks when sending an email. Receiving emails with cyrillic symbols works as expected (if they were encoded properly by the sender, so the message sent by Wino is still broken even outside Wino while reading).

**Comment by bkaankose** [comment]
Thanks for the report. Got feedback for Chinese as well.

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/8c21bae2-020d-4d8d-96f0-8dbe660d4af4)

Looks like something is wrong with encodings.

**Comment by bkaankose** [comment]
1.7.2 went live today on Microsoft Store and this should be fixed in the release. Could you please give it a try again and close the issue if fixed?

Thanks.

**Comment by shoker537** [comment]
> 1.7.2 went live today on Microsoft Store and this should be fixed in the release. Could you please give it a try again and close the issue if fixed?
> 
> Thanks.

I confirm it's fixed for me! Thank you.
