### ISSUE TITLE
[Bug] Missing folder, Archive doesn't exist for this account

### ISSUE THREAD

**Issue by RoL0NL** [bkaankose/Wino-Mail#142]
**Describe the bug**
**Missing folder** Archive doesn't exist for this account
when clicking on the Archive button in an IMAP account (Non-Microsoft/Non-Google)

**Expected behavior**
The message should be moved to the folder called Archive

**Screenshots**
Yellow popup: **Missing folder** Archive doesn't exist for this account

**Additional context**
The 'Archive' folder _does_ exist, is called Archive and is pinned (shows up below INBOX/Sent/Drafts/Trash/spam), I had to manually enable synchronization for this folder. Is there a way to assign the archive folder manually?

**Comment by bkaankose** [comment]
This is indeed a bug in the app flow. Users must be able to configure special folders for any account at any time.

I'll include it in the next release.

Thanks.

**Comment by jpbandroid** [comment]
> This is indeed a bug in the app flow. Users must be able to configure special folders for any account at any time.
> 
> I'll include it in the next release.
> 
> Thanks.

That's true...
I encountered this as well when I was testing Wino, so it's great that this will be included soon!

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Users will be notified when needed folder is not available and they will be presented to a new dialog to setup their special folders.

Please give it a try with the latest version and close the issue if you think it's fixed in the release. @RoL0NL
