### ISSUE TITLE
[Bug] Crash When selecting Mail Spacing under Settings -> Personalization

### ISSUE THREAD

**Issue by EzraWard** [bkaankose/Wino-Mail#143]
**Describe the bug**
Wino 1.7.0 crashes when navigating to Settings -> Personalization and selecting Mail Spacing.

**Expected behavior**
No crash when selecting Mail Spacing.

**Comment by EzraWard** [comment]
[WinoDiagnostics.log](https://github.com/bkaankose/Wino-Mail/files/14947762/WinoDiagnostics.log)

Adding WinoDiagnostics.log.

**Comment by bkaankose** [comment]
Thanks for the report. I'm aware of this issue. It's due to one of those things I forgot to enable before releasing beta.

I'll get it done for the next release.

**Comment by bkaankose** [comment]
1.7.2 went live today on Microsoft Store and this crash is fixed. Please re-open the issue if you still encounter with the latest release.
