### ISSUE TITLE
1. Count number of unread emails only include the 'Focused' ones(not the marketing/other emails) 2. One click on the email's account instead of two to open the inbox

### ISSUE THREAD

**Issue by ahmedmn87** [bkaankose/Wino-Mail#144]
Hello,

I have 2 features proposal:

1. I think the count number of the unread 'Other' emails should not be included. Most of those emails are just marketing and we don't even open them. It might be great to see that the count number of unread emails only include the 'Focused' ones.

2. When I click on the email's account, it expands/unexpands it and it's fine but it should also show the Inbox. As of now, to see the inbox of an email's account, you have to do 2 clicks. The first one is to expand ir unexpand, the second is to click on 'Inbox'.

Thanks

**Comment by bkaankose** [comment]
1) This was reported before and it's fixed for the next beta version.
2) In the current beta version, menu navigation system is reworked to match Windows Mail. You have accounts on the top, as you click through accounts your folders are loaded. You can give it a try and let me know.

You can download the beta [from this link ](https://github.com/bkaankose/Wino-Mail/releases/tag/beta). If you experience certification issues during installation, [follow this guide here.](https://learn.microsoft.com/en-us/windows/application-management/sideload-apps-in-windows)

**Comment by bkaankose** [comment]
New version 1.7.2 went live on Microsoft Store today. Issues you mentioned are fixed in that release. Please re-open the issue if you think they are not fixed. @ahmedmn87
