### ISSUE TITLE
[Bug] Account Sidebar Does Not Remember State on App Launch

### ISSUE THREAD

**Issue by EzraWard** [bkaankose/Wino-Mail#145]
**Describe the bug**
The Account Sidebar is always expanded upon app launch, regardless of whether it was expanded when app was closed or not.

**Expected behavior**
If account sidebar is open on app close, it should remain open on subsequent app launch. If closed, it should be closed.

**Comment by bkaankose** [comment]
This is a good idea.

I have it already implemented for the next version.
Thanks!

**Comment by akamienski** [comment]
> This is a good idea.
> 
> I have it already implemented for the next version. Thanks!

Do you have an idea when you'll release it and if it'll include fix for .mailto protocol?

**Comment by bkaankose** [comment]
Closing as fixed.
