### ISSUE TITLE
[Bug] Address field for some IMAP accounts appears empty

### ISSUE THREAD

**Issue by chenseanxy** [bkaankose/Wino-Mail#149]
**Describe the bug**
For IMAP accounts requiring custom settings, address field appears empty in the accounts menu UI.

**Expected behavior**
This field should be filled in, as for other accounts like Gmail and Microsoft.

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/24606776/8a16d589-68b4-43f5-ad72-790c6f58017b)

**Additional context**

Upon further investigation, this seems to be more of a UX issue on account setup:

The origin of this empty info seems to be from when the account was created, address is populated from `customServerInformation.Address` which is empty;
https://github.com/bkaankose/Wino-Mail/blob/3ea6bd759ecfd20bd938df62119ee76bfcb590fe/Wino.Mail.ViewModels/AccountManagementViewModel.cs#L185

And this comes from the fact that when the user submits the 'Advanced IMAP Config' dialog, the email address field wasn't populated from the previous dialog; and thus on submission `customServerInformation.Address` stayed empty.

![image](https://github.com/bkaankose/Wino-Mail/assets/24606776/827ce4ef-8acd-43ff-ab57-a68f4e1a13c1)
![image](https://github.com/bkaankose/Wino-Mail/assets/24606776/686d443b-eb71-4f45-9dd1-97043a17f6c5)

I think this is very minor, and fix should be simple enough and I might do it at some point. Meanwhile, users can just make sure to fill in the address in the advanced dialog to mitigate this issue.

**Comment by bkaankose** [comment]
Good catch! I can agree that this is a UX issue in the app flow.
