### ISSUE TITLE
[Suggestion] UI Changes for account/folder list

### ISSUE THREAD

**Issue by Fric56** [bkaankose/Wino-Mail#152]
First of all, very cool that someone is making a new email client after Windows Mail is shutting down soon.
I also have two suggestions that would be important to me (that are also in the Windows Mail App): 

1. In my Outlook account I would like to see all mails at once and not have it filtered with "Focused" or "Other". 
2. I use 5 mail accounts and would find it clearer if the account bar on the left was structured in the same way as in Windows Mail. That at the top is the list of accounts and below the folders that belong to the selected account.

![Screenshot 2024-04-18 125614](https://github.com/bkaankose/Wino-Mail/assets/47680634/7409bbb0-e97f-4f5c-bb64-953a4e93099d)

**Comment by bkaankose** [comment]
1) You can disable Focused Inbox feature in Manage Account Settings. Click on the account and you will see the option here

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/0a673162-e3aa-4741-94d2-76ac4e82d9bb)

2) Menu navigation system is reworked in beta version as you mentioned like same as Windows Mail, but is not released to Store yet. Instructions on how to access beta releases are explained in the read me of the project.

**Comment by Fric56** [comment]
Ah, that's awesome. You'll get my support by buying the pro version. Thank you.
