### ISSUE TITLE
[Bug] Missing MailItemFolder in v1.7.0

### ISSUE THREAD

**Issue by Fric56** [bkaankose/Wino-Mail#153]
**Describe the bug**
I think the screenshot makes it clear, what I mean.
It was working in the release version.

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/47680634/42336968-c4ec-4bb0-926f-862f5b0496ca)

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Closing the issue since it's already fixed in the release.
