### ISSUE TITLE
[Bug] Hide scrollbars when nothing to scroll with windows accessibility feature

### ISSUE THREAD

**Issue by Tiktack** [bkaankose/Wino-Mail#159]
**Describe the bug**
Scrollbars shown even there enough space to show the content with enabled windows feature: 
Settings -> Accesibility -> Visual Effects -> Always show scrollbars

**Expected behavior**
Scrollbars should not be visible

**Comment by bkaankose** [comment]
@Tiktack I think this bug was fixed with #158

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Closing the bug since it's fixed in the release.
