### ISSUE TITLE
[Bug] Toggling Focused Inbox On/Off Does Change Inbox Until Restart of App

### ISSUE THREAD

**Issue by EzraWard** [bkaankose/Wino-Mail#164]
**Describe the bug**
When updating the setting for Focused Inbox to on/off in Manage Accounts -> [Account Name] -> Focused Inbox, the setting value (if changed) does not reflect in the email list for the account until Wino is closed and reopened.

**Expected behavior**
When updating the setting for Focused Inbox and navigating back to the account inbox the setting was changed for, the application should immediately reflect the settings change.

**Screenshots**
![WinoFocused](https://github.com/bkaankose/Wino-Mail/assets/52414057/21cf3d9f-3497-4bfe-949a-f5b762b5a6c3)

**Additional context**
N/A

**Comment by bkaankose** [comment]
I can confirm this bug. 

It's happening because changing the value in settings applies the change to database, but doesn't update the folder model in the menu. Therefore, when you navigate to the folder again it still thinks the folder has focused inbox enabled.

**Comment by Natriss** [comment]
@bkaankose I would like to reopen this, because the latest version in the Microsoft Store still has this issue.
