### ISSUE TITLE
Cannot see the addressees and people in cc for received mails

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#17]
I think they should be displayed under the sender and the object

**Comment by MarcAnt01** [comment]
@bkaankose I edited the title, the issue is for sent mails since the composer is not available yet

**Comment by bkaankose** [comment]
I think we can close this issue with the recent changes. There is still scrolling issue with lots of recipients, but the basic representation is there.

**Comment by MarcAnt01** [comment]
@bkaankose the implementation still looks very rudimental. If all the content is not displayed on a single line it gets cut

**Comment by MarcAnt01** [comment]
Can this be reopened?
![image](https://github.com/bkaankose/Wino-Mail/assets/43090263/783be5ff-7e21-407d-bfbf-b44359e712ce)
This is the current state of the future, even if it has been technically implemented, it's basically unusable from the final user
