### ISSUE TITLE
unverified error when trying to connect university mail? [Bug]

### ISSUE THREAD

**Issue by moondling** [bkaankose/Wino-Mail#178]
Firstly, I am extremely glad I found this app since the new outlook is a disaster, however, when I tried to  log in to my university account which is going through office 365 I get this error: 

![image](https://github.com/bkaankose/Wino-Mail/assets/116903495/51177a7f-7d4a-4a5e-af93-6aca7c7a03d1)

Is there anything can/should be done from your side? Or its purely admin management from my university?

Thanks 
Darius

**Comment by bkaankose** [comment]
Unfortunately Wino can't work with Microsoft 365 accounts at the moment, unless your administrator approves it explicitly.
