### ISSUE TITLE
[Bug] Mail synchronization problems

### ISSUE THREAD

**Issue by vk2r** [bkaankose/Wino-Mail#182]
First of all, I want to thank the effort made by the developer of this application. I have been looking for an alternative to Windows Mail, since the Windows 10-11 application is about to disappear. In fact, I have decided to support the development of this application, by paying for the full version, however, I have encountered some problems.

The first time I open the application it loads the mails without any problem, however, I noticed that it does not synchronize the mails correctly the following times. In Outlook Mail, emails arrive almost immediately, however, in Wine Mail it is not only difficult for the emails to arrive, but there have been times when the account simply does not synchronize, not even by pressing the "Synchronize account" button.

This makes it difficult to use Wine Mail, despite the nice interface, which sometimes forces you to go back to Outlook Mail to be able to check unopened emails.

I would expect the emails to sync correctly. Not at the speed of Outlook Mail, but at least, new emails would appear.

Have a nice day.

**Comment by Kryso57** [comment]
I agree with above, gorgeous interface, just what I was looking for,, BUT sync and making default client not possible/working in Win11 23H2. At startup I get this error panel "Denied Background Execution" Below it says "Background execution for this app is denied. This may affect synchronisation and live notifications". = not syncing /adding new emails 2nd time after adding a new account. Nowhere in settings can I allow Wino Mail to sync nor set it as default. SAD as when 1 goes back to MS mail it looks just SHI** but doe s sync.

**Comment by bkaankose** [comment]
New version went live today. Please give it a try with version 1.7.2. This release has a reworked synchronizer for Outlook, Gmail and IMAP.

@Kryso57 regarding the background execution, Wino Mail is a UWP app, which means it works in a sandboxed environment and prune to attacks from 3rd parties. Background synchronization is handled by different mechanism running in the background. You don't need to keep it open to keep recieving mails, but you must enable Wino Mail to run in the background if needed.

To get rid of that warning, right click to Wino Mail in startup menu and go to 'App Settings' : 

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/a8da85c6-2907-412f-9e82-708370f14a87)

and make sure this option is selected as 'Always'

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/392a3e8c-2f5b-4313-8f60-5c0fd24a8a37)

**Comment by Vinsup** [comment]
Same as above, I would love to switch to Wino Mail as my default mail client, but even the 1.7.2 fixed the issue on IMAP with my INBOX folder not being detected correctly, I am now facing the issue described here. Upon account creation mails are retrieved correctly, but synchronization do not get new emails afterwards.

And while writing this post, I switch the background activities to "Always" for the application as well as activating the logs for IMAP sync. And it somehow did start to synchronize again. Even if I had a IMAP synchronisation error message telling me that server was busy something... But still no IMAP logs available to share. 
I will come back here whenever they will be available.

**Comment by bkaankose** [comment]
> Same as above, I would love to switch to Wino Mail as my default mail client, but even the 1.7.2 fixed the issue on IMAP with my INBOX folder not being detected correctly, I am now facing the issue described here. Upon account creation mails are retrieved correctly, but synchronization do not get new emails afterwards.
> 
> And while writing this post, I switch the background activities to "Always" for the application as well as activating the logs for IMAP sync. And it somehow did start to synchronize again. Even if I had a IMAP synchronisation error message telling me that server was busy something... But still no IMAP logs available to share. I will come back here whenever they will be available.

IMAP logs are only logged during account creation if enabled to diagnose initial connectivity issues. Synchronizations won't be logged in detail after the initial setup.

Synchronization issues will be logged commonly though. Maybe those can help.

**Comment by bkaankose** [comment]
This effort is being tracked on #270 going forward.

Closing as duplicate.

**Comment by lefgeen** [comment]
Mail.ru: deleted messages reappear after sync
There is a sync issue with Mail.ru accounts in the latest version.

When deleting messages in Wino Mail, they disappear locally but return after the next sync.
On the Mail.ru web interface the deletion works correctly — messages are removed on the server and do not come back.

Steps to reproduce

Add a Mail.ru account.

Delete any message in the app.

Trigger sync or wait for automatic sync.

The deleted message appears again.

Expected
Local state should follow server state. Deleted messages should not be restored.

Notes

Regression in the latest update.

Only affects Mail.ru accounts.
