### ISSUE TITLE
[Proposal] Drag & Drop attachments

### ISSUE THREAD

**Issue by Tiktack** [bkaankose/Wino-Mail#188]
**Describe the solution you'd like**
Wino should allow drag and drop files when composing mail

**Is your proposal implemented in Windows Mail?**
No

**Additional context**
There are multiple ways how it can look
Below is my proposal how it can look. Feedback appreciated. @bkaankose 
Dropzone available as soon as any reading mail page hovered (including webview), but to drop file they have to be put inside dropzone. 

https://github.com/bkaankose/Wino-Mail/assets/22834937/bf2b8d7b-c5ae-4dc0-a68f-40941f4d4c20

**Comment by bkaankose** [comment]
This is cool, I like it :) Almost all major clients support this.

Do you want to work on it? @Tiktack

**Comment by Tiktack** [comment]
@bkaankose Sure :) 
Just to confirm, is proposed look fine for you or you wanna change something? 

1. Currently it utilize 100% space of tool bar. But it can be like telegram is doing (overlapping like 90% only): 

![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/af50259b-e5b4-4edf-a05d-8a4cf2d2839d)

2. Also, when do you think this dropzone should appear, 

-   1. File dragged at any place of Wino
-   2. File dragged into mail zone ( Currently in proposal video) 
-   3. File dragged exactly to toolbar

**Comment by x-iso** [comment]
apparently, this is broken in v2
