### ISSUE TITLE
Are archive/delete/mute buttons really necessary?

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#19]
Since those actions can already be performed in the context menu, I think it would be better to hide them and place the search bar there saving space. Alternatively they could be put in the more options button. I feel like the upper part of the app is a waste of space

**Comment by bkaankose** [comment]
When everything started 2 years ago, I wanted to make things similar to Mail app to gain people's attention and you are right, that part is a waste of space.

However, right now I don't want to introduce major UI changes without making the initial functionality working. Ideally, I want to move search to center of the title bar like Store, and change this top command bar. Not sure what to do. Need to talk to some designer folks for their unique ideas :)

**Comment by roxk** [comment]
Yes. Having a button is better for e.g. touch without having to invoke the context menu.

**Comment by MarcAnt01** [comment]
> Yes. Having a button is better for e.g. touch without having to invoke the context menu.

I am primarily a touch user and I do not find it necessary, since in any mail/messaging app I expect a menu to be there and buttons are for actions which are not meant to be performed with a high frequency

**Comment by AkazaRenn** [comment]
I'm wondering if we can have some hover-over action buttons, both Outlook and Gmail do that, so I assume it has a high demand.

Gmail:
<img width="254" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/620cef54-fdb7-47dd-b4c0-cbc4f842fd89">

Outlook:
<img width="265" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/ace7cb19-1cfd-4284-81aa-2ec3138c6a94">

**Comment by AkazaRenn** [comment]
> When everything started 2 years ago, I wanted to make things similar to Mail app to gain people's attention and you are right, that part is a waste of space.
> 
> However, right now I don't want to introduce major UI changes without making the initial functionality working. Ideally, I want to move search to center of the title bar like Store, and change this top command bar. Not sure what to do. Need to talk to some designer folks for their unique ideas :)

Just my personal preference, I think the current design that limits the search box on top of mail list is better, because it indeed searches for mails. It would also make the whole interface more organized by avoiding having controls unaligned with anything else... I don't quite like how Microsoft Store and Task Manager does that.

**Comment by bkaankose** [comment]
I have converted one of the proposals on this matter to a discussion. 

Let's continue discussing better options for the action bar there #220
