### ISSUE TITLE
Rounded corners in WebView not consistent [Bug]

### ISSUE THREAD

**Issue by edge261** [bkaankose/Wino-Mail#192]
**Describe the bug**
The rounded corners in WebView are not consistent in the new mail screen compared to the main screen.

**Expected behavior**
Rounded corners, at least the top left corner, keeping consistency.

I'd like to propose...(I don't code, so idk how to do it) but it would be cool to have the webview "floating", with the 4 rounded corners visible... a little bit like Edge or Arc. If not possible, at least it would be good to make the rounded corners consistent in all the instances of the app.

**Screenshots**
Rounded corners in main mail view:
![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/0f37ea7d-8e61-429a-9d70-e1a98978394e)

Rounded corners in "new mail" view:
![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/63414cb2-9a68-4adb-bc9c-393f15e04883)

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Please confirm the fix and close the issue. @edge261

**Comment by edge261** [comment]
the original issue is fixed, however, there's still a inconsistency:

The signature editor has only 2 of 4 corners rounded. I think the webview is bigger than shown, that's also why the scrollbar doesn't fit the size of the view.

![image](https://github.com/bkaankose/Wino-Mail/assets/79731301/ec96b6a0-08b4-4c1b-a3bd-bdb2aa9ff28b)
