### ISSUE TITLE
[Bug] Email not being synced

### ISSUE THREAD

**Issue by SD777x** [bkaankose/Wino-Mail#194]
**Describe the bug**
Email is not fully synced on some accounts, sporadic, sometimes it's synced, sometimes not.  Today on my primary account it's only synced to 5/10/24, and the circle/sync icon is greyed out. 

**Expected behavior**
Email should be synced to date

**Screenshots**
![Screenshot 2024-05-24 121801](https://github.com/bkaankose/Wino-Mail/assets/36245422/1ad9823f-1109-4cb8-80f1-7b4c36619577)

**Additional context**

**Comment by Tiktack** [comment]
From screenshot I can see that it's still in progress of syncing ( bar under account name). During that time sync button is disabled. 
I also noticed such bug earlier. So my solution was to remove account and add it back, and while it syncs do not close wino.

**Comment by edge261** [comment]
It happens to me also.

Worst thing is that the sync stops :(

**Comment by SD777x** [comment]
> From screenshot I can see that it's still in progress of syncing ( bar under account name). During that time sync button is disabled. I also noticed such bug earlier. So my solution was to remove account and add it back, and while it syncs do not close wino.

I've left it in that sync state for probably an hour and it never fully synced, just stay stuck there.  I thought it was only temporary, but seems like it's permanent as that account still is set to May 10 every time I open the app up.

**Comment by bkaankose** [comment]
This was an issue with MS Graph SDK - UWP combination. It must be fixed for the 1.7.2 release which went live on Microsoft Store today.

Could you please give it a try and close the issue if it's resolved? @SD777x

**Comment by bkaankose** [comment]
Closing as fixed. Please re-open if you still encounter it.
