### ISSUE TITLE
Comboboxes in the personalization section?

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#20]
I think there's no point of showing all the current options, just display a combobox, from which they can be changed, since it's not something thought to be done a lot of times. I find the current ux a bit confusing
![image](https://user-images.githubusercontent.com/43090263/228847865-b6cced33-bdba-406f-8352-4062226ea761.png)

**Comment by bkaankose** [comment]
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/ab2c17a8-5c22-47de-a935-56f4ddc55324)

This is what I come up with in the new version. 1.6.2 is expected to be released today in Microsoft Store. @MarcAnt01 give it a try and please feel free to close the issue.
