### ISSUE TITLE
[Bug] No trash folder

### ISSUE THREAD

**Issue by imJarkko** [bkaankose/Wino-Mail#203]
I can't see trash folder. Deleted mails go to the void. 
I have folder synchronization on with Trash folder, am I missing something? 
I used three different gmail accounts and none of them have trash folder.

![Trash](https://github.com/bkaankose/Wino-Mail/assets/171178492/7b447d09-5afe-4e48-bf8a-6f5cd7dc4230)
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bkaankose** [comment]
Gmail hides some folders through API. Can you please make sure that they are not marked as hidden in Gmail web portal?

**Comment by imJarkko** [comment]
Yes that was it thank you!
