### ISSUE TITLE
[Bug] É À Ç Û Special characters not showing correctly 

### ISSUE THREAD

**Issue by Ralshi02** [bkaankose/Wino-Mail#205]
When sending or receiving an email containing special characters like "É Ç À Û", these characters will be replaced by unrelated characters.

![image](https://github.com/bkaankose/Wino-Mail/assets/77018515/5ad4e253-e705-4597-83f4-7b816c729bfc)
Here the word is "présent", but instead it displays as "prÃ©sent".

**Comment by bkaankose** [comment]
Thank you for the issue.

Somebody else also reported this in Discord channel. I remember trying it with Beta version and I was not able to reproduce it. Could you please give [Beta version ](https://github.com/bkaankose/Wino-Mail/releases)a try?

**Comment by bkaankose** [comment]
This should be fixed with the latest Store version.
