### ISSUE TITLE
[Proposal] 2 types of signatures per account: New email/Reply email 

### ISSUE THREAD

**Issue by AliakseiVenski** [bkaankose/Wino-Mail#207]
**Describe the solution you'd like**
It'd really nice to have 'New email' signature, which is full, and second one for 'Reply mail', which you can set as a short version of your Full one. Gmail and outlook in O365 have this. I noticed that no mail apps from store have it. It'd be a true killer feature of your app along with HTML signature, which is already proposed there as I see.

**Is your proposal implemented in Windows Mail?**
Not sure.
Wino's priority is to catch up with the feature set of Windows Mail first. 

**Additional context**
Gmail web settings:
![Screenshot_1](https://github.com/bkaankose/Wino-Mail/assets/36035128/4dec4111-29da-421b-810f-94257eda3d4d)

**Comment by bkaankose** [comment]
It's a nice suggestion. I liked it. Signature feature revamp is needed for sure. Including this would be great enhancement in that patch.

**Comment by Tiktack** [comment]
I will try to implement some proposal soon

**Comment by bkaankose** [comment]
Version 1.7.2 is released to Microsoft Store today. Closing the issue since this is implemented by @Tiktack in #217
