### ISSUE TITLE
[Proposal] Local cache

### ISSUE THREAD

**Issue by Shomnipotence** [bkaankose/Wino-Mail#208]
**Describe the solution you'd like**
The mailing list must be re-fetched on every startup. The mailing list should be cached, then fetched on startup, compared with the current content, and dynamically loaded when new content is available.

**Comment by Tiktack** [comment]
What do you mean re-fetched? Yes, every time you open mail list it queries Sqlite DB. Local DB very fast ( for UI it won't be noticeable it's from memory or from cache). Also, if you are using store version, I believe it lists a lot of emails, beta version lists only 20 items on initial render. 
Also, some slowness comes from setting that enables threads, but in beta version for outlook/gmail threading strategy performance was also improved.

**Comment by bkaankose** [comment]
I am completely against the caching personally. I see some benefits, but managing cache in this environment will just be complete mess. I don't think the burden it brings is bigger than the benefit at this point.

Mail initialization is already very fast. Thanks to @Tiktack's improvement on #173 it's already faster. I don't see a benefit in caching at the moment.

**Comment by bkaankose** [comment]
This will not be worked on. Closing the issue.
