### ISSUE TITLE
[Proposal] Separate zones visually 

### ISSUE THREAD

**Issue by Tiktack** [bkaankose/Wino-Mail#209]
**Describe the solution you'd like**
I saw some comments to separate zones visually and decided to try how it looks like. Inspired by Microsoft Store I made some mockup. 
Yes, they are eating some screen space ~15px in width and ~15 in height. 

But it looks pretty cool. Any feedback appreciated. 
Spacing, radius corner can be adjusted. Also, I am not sure about separation between email title/cc/to and email content.

**Additional context**
Before: 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/1bd98085-fddc-4a11-a734-81aa4976482e)

After: 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/66d80e36-ca2e-417f-8833-bca4677bb2cf)

**Comment by edge261** [comment]
To be honest, I love it. It is what I had in mind when I made one of those comments.

in both ways (separated from email header or together) it makes sense.

maybe you could try first without separating the email header... and see the reactions.

**Comment by EzraWard** [comment]
I really like it. Creates visual separation of the different components of the UI.
