### ISSUE TITLE
[Proposal] Combined Inbox Support

### ISSUE THREAD

**Issue by hisra015** [bkaankose/Wino-Mail#211]
I would like a combined inbox to be implemented so that I can easily see all email without having to sort through all my accounts

This has already been implemented in the Windows Mail and Calendar application. It has been removed in the new Outlook application however.

**Comment by bkaankose** [comment]
It's already implemented in Beta version.

I am working on latest small fixes before the release. Combined/Merged/Linked inbox feature will go live in the upcoming days. 
You can join the discussion here.

https://github.com/bkaankose/Wino-Mail/discussions/189

**Comment by lostmsu** [comment]
I might be blind, but how do I open unified Inbox?

**Comment by bkaankose** [comment]
> I might be blind, but how do I open unified Inbox?

1) Go to Manage Accounts menu and click here
![image](https://github.com/user-attachments/assets/2beb4abb-52d2-4b7e-a722-f85f071c2c74)

2) Give it a name
3) Move the accounts you want to merge together to the left and click save.

**Comment by lostmsu** [comment]
On first attempt doing this I put "All" in the name, hit OK, and nothing happened. The dialog closed, no error was shown, but thew linked account was not created.

On the second try with different name it worked.
