### ISSUE TITLE
[Proposal] Better thread UX

### ISSUE THREAD

**Issue by clragon** [bkaankose/Wino-Mail#214]
**Describe the solution you'd like**
When I click on an E-Mail thread (multiple E-Mails grouped together), 
it should unfold but also immediately select the latest E-Mail in the thread.

Right now, clicking on a thread just unfolds it. 
This is very slow and confusing.

Additionally, threads do not work with select (shift/ctrl). As soon as an E-Mail in a thread is selected, 
only E-Mails inside that thread can be selected. Therefore, threads can not be deleted/archived together with non-thread E-Mails.

**Is your proposal implemented in Windows Mail?**

Yes. When clicking an E-Mail thread in Windows Mail, it unfolds and opens the latest E-Mail in the reading pane.
Additionally, when a thread is selected, or shift-selected as part of a larger selection, all its E-Mails are selected alongside it.

**Additional context**
N/A

**Comment by Tiktack** [comment]
Should be fixed, the same as #338
