### ISSUE TITLE
[Bug] `We can't connect to the service you need right now.'

### ISSUE THREAD

**Issue by cuij89** [bkaankose/Wino-Mail#215]
**Describe the bug**
When I logging in the organization account from the outlook option, the software tells we can't connect the service you need right now ...

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/102997975/0e68a8cf-b48e-4448-b969-cc465985f3fb)

**Comment by bkaankose** [comment]
This happens sometimes on the Microsoft side. Wino has nothing to do with it. Services might be down for MS Graph, or you might have some applications that listens to your network, like a HTTP debugger.

**Comment by bkaankose** [comment]
Closing the issue since it's not Wino related.
