### ISSUE TITLE
[Proposal] Auto clear search filter when search query is removed

### ISSUE THREAD

**Issue by AliakseiVenski** [bkaankose/Wino-Mail#216]
**Describe the solution you'd like**
It is related to the search bar on the main screen. I think most mail clients have this feature.
Usually when you type something there and get the results you need, you just remove your search words by `Del` or pressing 'x' button.
- It would be really convenient to reset a search filter when you push 'x', at least. Ideally - also when you clear search field with 'Del', so all cases are covered.

**Is your proposal implemented in Windows Mail?**
Yes

**Comment by Tiktack** [comment]
It's already implemented in main branch. 
You can check this PR for all changes to search.
#185 

Issue should be closed

**Comment by bkaankose** [comment]
Labeling as fixed to be checked after the release.

**Comment by AliakseiVenski** [comment]
![mail](https://github.com/bkaankose/Wino-Mail/assets/36035128/71cfb45d-937f-4651-845a-6a13c62bfd69)

**Comment by AliakseiVenski** [comment]
I have such bejaviour.

**Comment by bkaankose** [comment]
> ![mail](https://private-user-images.githubusercontent.com/36035128/339146638-71cfb45d-937f-4651-845a-6a13c62bfd69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzExMzAsIm5iZiI6MTcxODIzMDgzMCwicGF0aCI6Ii8zNjAzNTEyOC8zMzkxNDY2MzgtNzFjZmI0NWQtOTM3Zi00NjUxLTg0NWEtNmExM2M2MmJmZDY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIyMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOGQ4ZDVkN2FjNTg1ZjhlMzZjYjJlZDk2NWY2MDIxM2ZhN2RjMzg0MTZmNmM3NWNkMGJiNDE2NjU4MzI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQxLB_c6NY7jJon7kv_UDtiODrqlEiXna9fkVufX_1U) [ ![mail](https://private-user-images.githubusercontent.com/36035128/339146638-71cfb45d-937f-4651-845a-6a13c62bfd69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzExMzAsIm5iZiI6MTcxODIzMDgzMCwicGF0aCI6Ii8zNjAzNTEyOC8zMzkxNDY2MzgtNzFjZmI0NWQtOTM3Zi00NjUxLTg0NWEtNmExM2M2MmJmZDY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIyMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOGQ4ZDVkN2FjNTg1ZjhlMzZjYjJlZDk2NWY2MDIxM2ZhN2RjMzg0MTZmNmM3NWNkMGJiNDE2NjU4MzI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQxLB_c6NY7jJon7kv_UDtiODrqlEiXna9fkVufX_1U) ](https://private-user-images.githubusercontent.com/36035128/339146638-71cfb45d-937f-4651-845a-6a13c62bfd69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzExMzAsIm5iZiI6MTcxODIzMDgzMCwicGF0aCI6Ii8zNjAzNTEyOC8zMzkxNDY2MzgtNzFjZmI0NWQtOTM3Zi00NjUxLTg0NWEtNmExM2M2MmJmZDY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIyMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOGQ4ZDVkN2FjNTg1ZjhlMzZjYjJlZDk2NWY2MDIxM2ZhN2RjMzg0MTZmNmM3NWNkMGJiNDE2NjU4MzI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQxLB_c6NY7jJon7kv_UDtiODrqlEiXna9fkVufX_1U) [ ](https://private-user-images.githubusercontent.com/36035128/339146638-71cfb45d-937f-4651-845a-6a13c62bfd69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzExMzAsIm5iZiI6MTcxODIzMDgzMCwicGF0aCI6Ii8zNjAzNTEyOC8zMzkxNDY2MzgtNzFjZmI0NWQtOTM3Zi00NjUxLTg0NWEtNmExM2M2MmJmZDY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIyMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOGQ4ZDVkN2FjNTg1ZjhlMzZjYjJlZDk2NWY2MDIxM2ZhN2RjMzg0MTZmNmM3NWNkMGJiNDE2NjU4MzI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQxLB_c6NY7jJon7kv_UDtiODrqlEiXna9fkVufX_1U)

Did you built this version from main branch yourself? Or is it the Store version? Store version is pretty outdated and almost 6 months old now :)

**Comment by AliakseiVenski** [comment]
Oops, its from store... I thought it is update date there. I'll build latest version then. Thanks!

**Comment by bkaankose** [comment]
Version 1.7.2 is released to Microsoft Store today. Closing the since it's fixed.
