### ISSUE TITLE
[Bug] Account creation failure

### ISSUE THREAD

**Issue by Basti-3** [bkaankose/Wino-Mail#224]
**Describe the bug**

When trying to add an Imap Account using advanced configuration, the process fails with the following error: "account creation failed - IMAP client pool failed". 

**Expected behavior**
Previously, I was able to add all my accounts with no issue, and they functioned without issue.

**Additional context**
After the new update, I added my Outlook email account and then tried to add an IMAP mail account using the advanced configuration. Only every time I am done adding all the information and I try to create it, I get the following error: "account creation failed - IMAP client pool failed".

![Screenshot 2024-06-15 162541](https://github.com/bkaankose/Wino-Mail/assets/172915565/5d307e2f-90af-4695-9505-7cddefd50f3a)

**Comment by bkaankose** [comment]
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/71731211-95d7-4fe2-9471-7117b5a73cc5)

It doesn't matter how many years you do this job. You can always find some missing critical parts in the code like this one :) Having tests would've prevent this, but it is what it is unfortunately...

Basically what is happening here is that connection fails, but app thinks it didn't and starts preparing folder synchronization with an invalid connection details.

I will release a hotfix just to address this issue tonight.

**Comment by bkaankose** [comment]
1.7.3 went live few minutes ago. Please upgrade Wino and try again.

If you still encounter issues, please share the Mailkit protocol log. This is a log file that does not share any private information liek your credentials, but just the communication exchanged between IMAP server and Wino. You will find a new dialog to share this log very easily if the connection fails.

**Comment by bkaankose** [comment]
1.7.4 is released today that fixes this issue. Could you please try again and close the issue if it's fixed?
