### ISSUE TITLE
[Proposal] Better app icon

### ISSUE THREAD

**Issue by ottozumkeller** [bkaankose/Wino-Mail#225]
Would it be possible to change the design of the app icon back? The previous icon looked unique and modern and fit well with other windows apps, the new one reminds me more of a mobile app.

**Comment by Tiktack** [comment]
I like the new one more.

**Comment by bkaankose** [comment]
This is very controversial topic. I asked people to help with the icon design, made AI generate couple, hired a graphic designer to draw an icon. Possible outcomes have been voted in the Discord channel and this was the winner :)

Previous icon was something I found online. I don't even remember if I just stole somebodies work or it was free to be honest, it was long time ago. This one is at least unique and belongs to Wino Mail.

**Comment by Lisa24Jackson** [comment]
In my opinion, the current icon is too bulky and doesn't quite fit into the Windows interface. Most importantly, because of this, it's hard to read on small screens or from a distance greater than 30 cm. The previous one was clear. You could immediately tell it was a mail application, whereas now you have to scrutinize the icon to understand which app it represents. On the GitHub page, it's large and looks fine, but within the system, it's considerably smaller, exacerbating the readability issue.

**Comment by MilkTeaCat52** [comment]
I agree that the new icon looks good close up but doesn't work as well with smaller sizes. The icon is also a bit too long vertically.

Most importantly, the icon kinda doesn't make sense logically; the letter is triangular and folded while the envelope has a flat edge. Quirks of generative AI I guess.

**Comment by bkaankose** [comment]
I won't hesitate to change the icon again to be honest. I agree that something is missing in the new icon. Open for ideas.

Labeling the issue as 'help wanted'

**Comment by Lisa24Jackson** [comment]
@bkaankose I think increasing the envelope itself on the icon should be enough to make the icon appear better. Here's a comparison of the current icon and the one with the increased envelope:

![comparison](https://github.com/bkaankose/Wino-Mail/assets/155259522/2a81d182-8dc8-41af-9deb-e0c3dc5c6df3)


I used "LargeTile.scale-400.png" as the base, which is the highest resolution icon I found in the repository. Below is the finalized version of the icon attached.

[Wino Mail.zip](https://github.com/user-attachments/files/15913834/Wino.Mail.zip)

**Comment by bkaankose** [comment]
A simple envelope with fluent design essences should do the work. Now reading the critics in this issue, I agree that current icon feels a bit off.

**Comment by alekberovf** [comment]
This new icon not displaying properly on Windows 10 lockscreen 
![5469895247120162080_121](https://github.com/bkaankose/Wino-Mail/assets/174000883/40b0daba-0556-4ad7-9b0d-c633e565fcca)

**Comment by bkaankose** [comment]
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/6c7bd00e-b10a-4e36-aa34-0b4d359c2fb6)

New icon is created by **astrox809** in our Discord channel :) I hope this satisfies everybody.
Closing the issue.
