### ISSUE TITLE
[Proposal] Aptos font availability - let users choose their font

### ISSUE THREAD

**Issue by edge261** [bkaankose/Wino-Mail#226]
**Describe the solution you'd like**
Ideally, I'd like to use Aptos as a default font. However, I'm not sure if their license enables it... 

**Is your proposal implemented in Windows Mail?**
Yes, it's implemented. You can choose from all fonts installed.

**Additional context**
All fonts of the OS are covered by the same terms, as mentioned here: 
https://learn.microsoft.com/en-us/typography/fonts/font-faq
https://learn.microsoft.com/en-us/typography/font-list/aptos

I have in mind a workaround to this: Allow people to type in the font name they want to use. Or make Wino read all fonts installed and let users choose from there.

**Comment by bkaankose** [comment]
I would like this to be implemented for sure. Users must be able to use whatever font is available in the system.

Technical challenge here is that Wino uses Quill WYSIWYG editor internally to compose mails. This editor has its own fonts pre-defined. I am not a web developer. Personally making customizations on Quill using TS/HTML/CSS was something I would like to delegate to somebody else if possible 💯 

Marking the issue as 'help wanted' to see if somebody willing to help on this implementation for now.

**Comment by Tiktack** [comment]
I will check what we can be done with fonts in a weview

**Comment by Tiktack** [comment]
Just realized, I don't understand exactly what is needed? 

- Font for reading emails - what should happen if sender set specific font? change it to selected in wino? But if it's promotional emails it may look them different, shift layout and so on. 

- Font for composing emails - if receiver doesn't have this font available? fallback to default?

**Comment by edge261** [comment]
> Just realized, I don't understand exactly what is needed?
> 
> * Font for reading emails - what should happen if sender set specific font? change it to selected in wino? But if it's promotional emails it may make them look different, shift layout and so on.
> * Font for composing emails - if receiver doesn't have this font available? fallback to default? But if you set some unique font, it will happen for all ur receivers...

Font for composing emails... if receiver doesn't have the font available the mail client should fallback to default.

**Comment by bkaankose** [comment]
v1.9.0 is released to the Store today which allows users to set installed fonts on the system.

Closing as completed.
