### ISSUE TITLE
[Bug] Reply chain not included in a new reply

### ISSUE THREAD

**Issue by edge261** [bkaankose/Wino-Mail#227]
**Describe the bug**
The chain of replies of an email is not included when you reply from Wino.

**Expected behavior**
To include those replies.

**Additional context**
Adding this issue so it can be developed.

**Comment by bkaankose** [comment]
v1.7.6 is released today. This should be fixed. Please give it a try and close the issue if you think it's fixed.

**Comment by edge261** [comment]
Issue fixed. Thank you!
