### ISSUE TITLE
Cannot add Google Account

### ISSUE THREAD

**Issue by prakashgd** [bkaankose/Wino-Mail#23]
After Oauth google breaks the authorization saying app accessing sensitive Infos
![image](https://github.com/bkaankose/Wino-Mail/assets/5779746/a87aa71c-14a9-420f-94f4-686b07448bca)

**Comment by eskori** [comment]
Same thing here. Process:

1. Downloaded from Windows Store (first install ever).
2. Clicked on _Manage Accounts_ -> _Add account_ -> _Gmail_ -> _Create account_ 
3. Logged in to my account in the browser. 
4. Got the error message:
> ![image](https://github.com/bkaankose/Wino-Mail/assets/72322314/f60ecf99-1fd3-4b4e-abf9-ea4d260f15d1)

Some details:

- Wino Preview v1.3.1.0 
- Windows 11 Pro 23H2 v25387.1 (Canary Insider Preview)

**Comment by bkaankose** [comment]
Thank you for the report. I wasn't aware of this issue, and as @eskori mentioned I'll be tracking this one in #8 going forward.
