### ISSUE TITLE
[Proposal] Publishing the app in "EXE" format

### ISSUE THREAD

**Issue by Lisa24Jackson** [bkaankose/Wino-Mail#230]
Sorry if this is a duplicate and the topic has already been raised, but I did look beforehand and couldn't find anything. If it's not too much trouble for the author, I'd greatly appreciate it if, in addition to the Microsoft Store format "MSIX", you could also build and publish the app in "EXE" format. I understand that creating the app in "EXE" format may be more cumbersome than in "MSIX", and automatic updates won't work in that case, but it would be great to have the option to install the app outside of the Microsoft Store. I think many would appreciate that.

**Comment by Tiktack** [comment]
Please no.

**Comment by bkaankose** [comment]
Wino Mail is [UWP application](https://learn.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide). UWP apps can only be distributed via Microsoft Store.

When Windows App SDK improves, I will convert UWP app to Windows App. Then we'll be able to distribute standalone installer for this project. Until then it's not possible unfortunately.

**Comment by Lisa24Jackson** [comment]
@bkaankose 
Clear. Thanks for the explanation.
