### ISSUE TITLE
[Bug] SyncRoot error

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#235]
**Describe the bug**
Sometimes I get following error:

"Synchronization Failed. The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads."

**Expected behavior**
No error, normal synchronization.

**Screenshots**
<img width="536" alt="Screenshot 2024-06-19 152601" src="https://github.com/bkaankose/Wino-Mail/assets/2843963/754c8e4e-78fb-4b68-ae54-a30ed13ab72f">

**Additional context**
This is in version 1.7.3 from Microsoft Store.

**Comment by bkaankose** [comment]
1c96c0ccbfd253875c0ccd38b4643858bd6dfb9f and 150bf124a95343cd98bb6f01cb328c8b84379614 should fix this. Labeling as fixed for now.

**Comment by bkaankose** [comment]
1.7.4 is released today. This version has better handling of the imap connections created. Could you please try to reproduce this error on your end?

**Comment by EvilVir** [comment]
Ok, I will check. So far so good, but found another issue. Reporting now.

**Comment by bkaankose** [comment]
Closing this issue as fixed.
