### ISSUE TITLE
[Bug] Collection modified error.

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#236]
**Describe the bug**
If I click too fast through list of accounts and folders, I sometimes get "Collection has been modified" error. It looks like there's general problem with bringing list of mails to UI. This is not the only bug around that area I experience. I had already seen random application crashes when clicking around, HTTPClient busy errors etc. If you for example try to delete multiple e-mails one by one, it often doesn't do that and just deleted e-mail gets back to the list.

**Expected behavior**
No errors :)

**Screenshots**
Wasn't fast enough to catch it. Will try to upload later in this ticket.

**Additional context**
Version 1.7.3 from Windows Store.

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
