### ISSUE TITLE
[Bug] Response handling failed with error HTTP code BadRequest

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#237]
**Describe the bug**
When quickly deleting one email after another from the Outlook inbox I get "Response handling failed with error HTTP code BadRequest" error.

**Expected behavior**
No error :)

**Screenshots**
<img width="454" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/2843963/e9cf643f-3044-481d-8e81-2552725a7de9">

**Additional context**
Version 1.7.3 from Windows Store, Outlook.com account. Looks like it doesn't happen with Gmail account.

**Comment by EvilVir** [comment]
Got a new one in latest version (1.7.6.0):

![image](https://github.com/user-attachments/assets/17c325ed-8f73-4c8c-ab4e-9245fb9a46d8)

**Comment by bkaankose** [comment]
This issue is now tracked here. #290 

Closing as duplicate. Original issue is fixed in beta release. You can give it a try and leave a comment if you experience issues.
