### ISSUE TITLE
[Bug] Changing mailbox during loading breaks app

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#241]
**Describe the bug**
One of my mailboxes takes longer time to open (again the Nazwa.pl one, I reported for other bug previously). So when I open Wino and it starts loading that mailbox I then click on other mailbox and that second one is not opening ("Folder empty"). Instead after some period of time the first mailbox's contents are displayed despite the second one is selected and highlighted. Sometimes, but not always, when I click away back to first mailbox application crashes totally and closes.

**Expected behavior**
I should be able to jump between mailboxes smoothly, even if one of them is currently synchronizing or otherwise busy. Application should not display me contents of anything else than currently selected.

**Additional context**
Version 1.7.3 from Windows Store

**Comment by chenseanxy** [comment]
Can you confirm that:

- You are using threads (Settings -> Message List -> Conversational Threading)
- The other inboxes you don't have issues with, is either MS Outlook or Gmail accounts

**Comment by EvilVir** [comment]
1. Yes:
 
<img width="699" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/2843963/fde74b0d-ea4c-478f-ab12-430395e199b8">

2. Yes, rest of them are Outlook or Gmail, only one plain IMAP. I have some issues, reported elsewhere, with MS Outlook.

**Comment by EvilVir** [comment]
It does look better, I will give it a ride tomorrow during normal work day and will circle back here. Thanks!

**Comment by bkaankose** [comment]
This issue should be fixed in the latest version 1.9.0. Please re-open if you still experience it.
