### ISSUE TITLE
[Bug] After clearing the trash, the cursor inexplicably jumps to the search field

### ISSUE THREAD

**Issue by Lisa24Jackson** [bkaankose/Wino-Mail#243]
I've noticed an annoying feature: after clearing the trash, specifically after deleting the last message in it, the cursor inexplicably jumps to the search field. This is somewhat irritating. In the previous version, I didn't notice this behavior.

**Comment by bkaankose** [comment]
1.7.4 is released today that fixes this issue.

@Lisa24Jackson could you please try again and close the issue if it's fixed?

**Comment by bkaankose** [comment]
Closing the issue as fixed for now. Please re-open if you think it's not fixed.
