### ISSUE TITLE
[Bug]When the new app store name is associated and packaging is completed, the following exception will be prompted when running the app

### ISSUE THREAD

**Issue by Shomnipotence** [bkaankose/Wino-Mail#245]
**Describe the bug**
When the new app store name is associated and packaging is completed, the following exception will be prompted when running the app

**Screenshots**
![3783470e81a60aa7854e1f75cdc08597](https://github.com/bkaankose/Wino-Mail/assets/6630660/5b7ba3bd-ab7d-46fd-bf71-7c7c767cf7f4)
![813fe49c9d19d6654a97920d0e62e64b](https://github.com/bkaankose/Wino-Mail/assets/6630660/adbcd9aa-04e0-45f6-a76b-ad7281b8a1fd)

Unhandled exception at 0x00007FFF25D4EE5A (KernelBase.dll) (in Wino.exe): 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x000000000000000, 0x000000000000000, 0x000000000000000, 0x00007FFF0CBD0000).

**Comment by bkaankose** [comment]
It's clear that this is not related to Wino itself even though I don't understand anything in Chinese. Make sure that your build environment runs fine and try again, or seek for a solution for the message on SO.

**Comment by chenseanxy** [comment]
Wait are you guys trying to simply repackage Wino and release it on the store?

**Comment by Tiktack** [comment]
> Wait are you guys trying to simply repackage Wino and release it on the store?

Looks like yes. They changed logo and author link and trying to release on the store. And even didn't hesitate to open this issue....

**Comment by bkaankose** [comment]
It is what is it. You can see my concerns about open-sourcing the code under this discussion #61. 

Anyways, nobody can re-package and re-distribute this work without open-sourcing their code and without a notice. This project is licensed under GPL-3. I won't hesitate to contact Microsoft internally for legal matters with Store on any action against the project license.

**Comment by Shomnipotence** [comment]
> It is what is it. You can see my concerns about open-sourcing the code under this discussion #61.
> 
> Anyways, nobody can re-package and re-distribute this work without open-sourcing their code and without a notice. This project is licensed under GPL-3. I won't hesitate to contact Microsoft internally for legal matters with Store on any action against the project license.

https://github.com/MicaApps/Wino-Mail
https://github.com/MicaApps/Wino-Mail/tree/backup4
https://github.com/MicaApps/Wino-Mail10

![image](https://github.com/bkaankose/Wino-Mail/assets/6630660/c6978bca-bb01-4392-a407-5b97abed6e9e)

Obviously, they are still open source
My main goal was to align it to my design, which I showed to the author when wino was not open source, but the author thought that the design did not fit the design style of Windows 11

**Comment by bkaankose** [comment]
I understand.

According to the license; as long as you keep your fork open sourced and a notice in the application that this is a fork of Wino, it is fine. You won't be breaking any law and I can't prevent you from releasing your own distribution.

You can as well keep your own donation link or your own add-ons to compensate for your work. License allows it. My aim was never to get rich by mail application, rather create a small community around the same purpose to re-create better version of deprecated Mail & Calendars. This way eventually the application will get better and better by contributions to achieve this goal.

What we will have in this case is that different people will contribute to Wino, and different people will contribute to your fork. We will be allowed to copying each other's work for fixes and improvements, but the UI and some functionality will differ. That is fine by me. In the end if people liked the functionalities more of your fork we can as well integrate them into Wino.

**Comment by Shomnipotence** [comment]
> I understand.
> 
> According to the license; as long as you keep your fork open sourced and a notice in the application that this is a fork of Wino, it is fine. You won't be breaking any law and I can't prevent you from releasing your own distribution.
> 
> You can as well keep your own donation link or your own add-ons to compensate for your work. License allows it. My aim was never to get rich by mail application, rather create a small community around the same purpose to re-create better version of deprecated Mail & Calendars. This way eventually the application will get better and better by contributions to achieve this goal.
> 
> What we will have in this case is that different people will contribute to Wino, and different people will contribute to your fork. We will be allowed to copying each other's work for fixes and improvements, but the UI and some functionality will differ. That is fine by me. In the end if people liked the functionalities more of your fork we can as well integrate them into Wino.

I won't leave my donation link in there, I need to keep the fork free. My goal, and the goal of the organization you see me forking from, is to make the old look app conform to Fluent Design System, and if possible, migrate the look framework to UWP/WinUI3.
---------------------------------------
Since I'm just a designer, I can't control the code quality, you can see that the code quality in the repository is not high. We actually tried to write a mail app twice, and finally had to give up and choose to modify the look based on wino code.

https://github.com/MicaApps/Mail
https://github.com/MicaApps/MailApp

Their code quality is not enough for this task.
----------------------------------------
In addition, I and other WPF developers have been troubleshooting this issue
Unhandled exception at 0x00007FFF25D4EE5A (KernelBase.dll) (in Wino.exe): 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x000000000000000, 0x00000000000000, 0x000000000000000, 0x00007FFF0CBD0000).

A problem in the Wino.exe process caused the process to fail to activate. The process has thrown one or more exceptions.
Please use Debug->Window->Exception Settings to configure the debugger to stop when these exceptions are thrown. You can find more information in the Debug pane of the Output window (Debug->Windows->Output).

**Comment by bkaankose** [comment]
I don't have anything specific setting that can cause this error to be honest. You might have faulty XAML somewhere, or a native exception in WinUI with your changes. If you just re-clone the repo and just change the package association it works fine on my end.

**Comment by Shomnipotence** [comment]
> I don't have anything specific setting that can cause this error to be honest. You might have faulty XAML somewhere, or a native exception in WinUI with your changes. If you just re-clone the repo and just change the package association it works fine on my end.

Yes, I just cloned the repository and modified the store association.
https://github.com/MicaApps/Wino-Mail13/tree/main

You can try to package the app again (if normal, you should see that it already has the store association information I used for testing purposes), then, you can package it once (I changed the package path to D:/Package, you can change it yourself)

Next, run the release mode again, and you will find that it will report a native error.
