### ISSUE TITLE
[Proposal] Button to clear the entire trash / Confirmation window when deleting any content from the trash

### ISSUE THREAD

**Issue by Lisa24Jackson** [bkaankose/Wino-Mail#246]
It would be great to have a button to clear the entire trash, as implemented in other e-mail apps.

Also, I would add that it would be desirable to implement a confirmation window when deleting any content from the trash, which is also present in other e-mail apps.

**Comment by bkaankose** [comment]
Empty folder functionality was implemented in the latest builds. Closing as fixed.
