### ISSUE TITLE
Old e-mail accounts will not be migred

### ISSUE THREAD

**Issue by Willi-Billi** [bkaankose/Wino-Mail#247]
**Describe the bug**
After the update, all e-mail account are deleted

**Expected behavior**
By a Upgrade I like to have a new, but working configuration

**Additional context**
If you make a new version, make a small part of software, that take the old
configuration & old e-mails to migrade to the new version.

**Comment by bkaankose** [comment]
I agree that it should not be happening, but the app is still in active development of features. Therefore, sometimes it's impossible to migrate old - new accounts. From version 1.6.4 to 1.7.2 there was almost 8 months of development and new synchronizers, which were not compatible with the 1.6.2 data model.

This is communicated in the welcome page of the application for the new version.
