### ISSUE TITLE
[Bug] Duplicated entries and other issues with e-mails lists

### ISSUE THREAD

**Issue by EvilVir** [bkaankose/Wino-Mail#251]
**Describe the bug**
I believe e-mails list population has a bug that, when user moves too fast between mailboxes, populates e-mails list with one of three wrong states:

1. "This folder is empty" message, when it is not.
2. Messages list from other account/folder.
3. Duplicated messages list.

**Expected behavior**
List of messages should always reflect what is currently selected in the mailboxes/folders section.

**Screenshots**
Example of duplicated e-mails:
<img width="331" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/2843963/7db4c136-1e7a-4291-9852-7c9a155c219f">

Another example, notice how e-mails aren't ordered properly anymore (like two sources tried to update same collection):

![image](https://github.com/bkaankose/Wino-Mail/assets/2843963/dc44b62f-8f0c-4ec1-98ff-1347b080d27d)

**Additional context**
Wino 1.7.4.0 from Windows Store.

**Comment by EvilVir** [comment]
And here's a screenshot of wrong e-mails displayed for selected mailbox (these are e-mails from 1st mailbox but 3rd one is selected):

<img width="509" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/2843963/173f6efe-5075-4055-ba59-617df6462aa8">

This situation happens mostly just after starting the application for the first time.

**Comment by EvilVir** [comment]
Also I get many crashes of the app in new version :(

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Can you update to the new version and retry?
