### ISSUE TITLE
[Proposal] Is there a way for the previous email threads to be automatically copied into a new reply?

### ISSUE THREAD

**Issue by StereogramStudios** [bkaankose/Wino-Mail#257]
On many email clients, when replying, it will copy all the text of the previous email into your draft and separate it with a line. The text is fully editable from there as well. 

Is there a setting for this? On mine currently, a reply draft is a blank draft, with no option to view the previous email I'm responding to, or to edit the previous email within my own draft.

**Comment by bkaankose** [comment]
Duplicate of #227

Let's track the issue there.
