### ISSUE TITLE
Bug on select email

### ISSUE THREAD

**Issue by luis206r** [bkaankose/Wino-Mail#261]
When an email is selected in the left panel, sometimes it display the inbox of another email. It should instead show the content for the right email that was selected. (I have 3 email accounts on Wino)

**Comment by bkaankose** [comment]
v1.7.6 is released today. This should be fixed. Please give it a try and close the issue if you think it's fixed.

**Comment by bkaankose** [comment]
Closing as fixed since you feedback is received for a month. Re-open if you encounter this issue again.
