### ISSUE TITLE
[Proposal] Russian localization

### ISSUE THREAD

**Issue by SODIX** [bkaankose/Wino-Mail#262]
**Describe the solution you'd like**
Russian speaks in CIS countries and Baltic states, over 300 million's of people. Please make good, literate Russian translation. 
**Is your proposal implemented in Windows Mail?**
YES.
**Additional context**
I can't use wino for now, for a two things, 1) My WIN10 is localized, while Wino is on full English, it ruin design and feel. 2) There is words in wino, which I don't understand. Basically there should be Latin(Spain), Chinese, Indian, Russian, Japan/Korean, German and Italian localization.

**Comment by Tiktack** [comment]
Обнови версию до последней, открой настройки дальше language& time и выбери русский язык.

**Comment by bkaankose** [comment]
Wino supports multiple languages thanks to our Crowdin community translators. Russian translation exists in the application.

Default language is English, but maybe we should start the application with system's language by default on the first run. It may be confusing for non English speakers to find the proper settings and change it.

I will close this issue as wontfix and track this default language effort in #265.
