### ISSUE TITLE
[Proposal] New UI Design

### ISSUE THREAD

**Issue by Shomnipotence** [bkaankose/Wino-Mail#266]
## Describe the solution you'd like ##
Many days ago I described the reason I opened a new branch because I aligned the design of Wino Mail to my design drawing

Now it's time to show it

![image](https://github.com/bkaankose/Wino-Mail/assets/6630660/447fb616-c81e-45ec-9fe4-b98de3091717)

## repository address ##
This is the GitHub repository address
https://github.com/MicaApps/Wino-Mail3

## commit record ##
This is its commit record, because it is based on an earlier Wino, so I had to re-submit it manually
https://github.com/MicaApps/Wino-Mail/tree/4

**Comment by bkaankose** [comment]
I don't plan to implement major UI changes to the app.

Closing the issue.
