### ISSUE TITLE
More stable background synchronization and notifications

### ISSUE THREAD

**Issue by Blueciffer1** [bkaankose/Wino-Mail#270]
**Describe the bug**
When the app is closed, which it is most of the time, no notifications are received despite knowing that I am getting an email. I am only alerted about an email whenever the the app is open. 

**Expected behavior**
Receiving indications about my emails even with the app closed

**Comment by rafae667** [comment]
The same happens to me. I noticed the email is only updated when I open the app. When I open it I see a lot of emails appearing and disappearing.

**Comment by P40L0X** [comment]
I have the same issue.
Notifications are not working at all on Windows 11 (24H2, Public Build 26100.1150)

**Comment by Xer0o** [comment]
The old Windows mail app used to run in the background using minimal resources, I wouldn't mind if Wino Mail did that to get notifications to work.

**Comment by artheadsgames** [comment]
Yeah, need to run it in the background to check new mails.

**Comment by bkaankose** [comment]
Here's the summary of investigation:

Analysis shows that the way Wino handles background synchronization is not optimal for every day usage. Patches done overtime to make it more stable didn't improve the existing background sync mechanism for everybody and architecture itself is unsufficient meet the requirements.

For the last couple days I've been working on some improvements to move background synchronization to a different process. This will make sure that Wino Mail application will be just UI, and all network operations and synchronization will be handled by a separate server process.

Technical feasibility work to find the optimal solution is still ongoing. Enabling [full trust](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.fulltrustprocesslauncher?view=winrt-20348), switching to WinUI, moving to OutOfProcessServer activatable options are on the table...

Going forward I will finish this work and release changes to Beta channel. I'll be closing all other issues about background sync as duplicate, and this issue will remain open for tracking/discussions.

**Comment by P40L0X** [comment]
> Here's the summary of investigation:
> 
> Analysis shows that the way Wino handles background synchronization is not optimal for every day usage. Patches done overtime to make it more stable didn't improve the existing background sync mechanism for everybody and architecture itself is unsufficient meet the requirements.
> 
> For the last couple days I've been working on some improvements to move background synchronization to a different process. This will make sure that Wino Mail application will be just UI, and all network operations and synchronization will be handled by a separate server process.
> 
> Technical feasibility work to find the optimal solution is still ongoing. Enabling [full trust](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.fulltrustprocesslauncher?view=winrt-20348), switching to WinUI, moving to OutOfProcessServer activatable options are on the table...
> 
> Going forward I will finish this work and release changes to Beta channel. I'll be closing all other issues about background sync as duplicate, and this issue will remain open for tracking/discussions.

Thank you for your investigation.
I still think Wino Mail currently has the best potential to fully replace Mail & Calendar once it will be completely phased out, so hopefully a new, fully working version (including Calendar) will be ready in time for it (end of 2024).

Keep up the good work ;)

**Comment by AkazaRenn** [comment]
I wish the server doesn't cause you any financial pressure that may cause the project to phase into a subscription model. However, I've paid for the multiple accounts upgrade hoping that can support this project by any bit!

**Comment by bkaankose** [comment]
> Thank you @bkaankose! I wish the server doesn't cause you any financial pressure that may cause the project to phase into a subscription model. However, I've paid for the multiple accounts upgrade hoping that can support this project by any bit!

Thank you for supporting the project. Server I mentioned is a local server, not a remote server that requires hosting. It's basically a separate always running process along with the actual app in your computer to handle synchronization.

Wino Mail will **always be free** to use up to 3 accounts and will **never** sell any additional add-ons.

**Comment by bkaankose** [comment]
Draft PR is ready #295 . Fixing couple more bugs until I release it for Beta channel. I believe it'll be ready to test this week for everybody.

I will request everybody in Discord channel to use it for couple days to see if it's stable or not. I believe 1-2 weeks of daily usage is enough to gather diagnostics and apply fixes. I don't think something major will pop up. With these estimations next month this work will be completed and released to Store for all users.

**Comment by zkkzkk32312** [comment]
not sure if this is related,
![image](https://github.com/user-attachments/assets/37153b2e-df66-46e0-b574-49684332817c)

**Comment by bkaankose** [comment]
> not sure if this is related, ![image](https://private-user-images.githubusercontent.com/13649949/354403527-37153b2e-df66-46e0-b574-49684332817c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTc3NzEsIm5iZiI6MTcyMjU1NzQ3MSwicGF0aCI6Ii8xMzY0OTk0OS8zNTQ0MDM1MjctMzcxNTNiMmUtZGY2Ni00NmUwLWI1NzQtNDk2ODQzMzI4MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAwMTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZTQ1N2Q1Mjk1YzY0MDVhZDYwZDRkNzM0Mjg4MGYxYWUyYzg1YjAwN2NiM2JkMmFkNWE4YzQzMjhmMDM1NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.biryxKzFMy9KME64pkfelUW3d1fc19WkWecAOp-mTqA)

Not directly, but it's indirectly contributes to the solution. That issue is tracked here #290. 

If you don't synchronize that much, folder delta links expire. Using those links returns 410 from the Outlook API. Having server synchronize every 3-5 minutes in the background will eliminate this issue happening.

**Comment by bkaankose** [comment]
It pleases me to close this issue... Finally, v1.9.0 is released to the Store with all the improvements I mentioned above. Please re-test the new version and let me know how it works for you.

**Comment by AlphaDeFcOn4** [comment]
The problem still persists, Wino mail is not working in the background on system tray. No e-mail or notification received.

**Comment by bkaankose** [comment]
> The problem still persists, Wino mail is not working in the background on system tray. No e-mail or notification received.

What is your configuration in Settings -> App Preferences?

It should look like this

![image](https://github.com/user-attachments/assets/5d3138fd-3edf-429e-a363-08cc2b341db2)

**Comment by AlphaDeFcOn4** [comment]
> > The problem still persists, Wino mail is not working in the background on system tray. No e-mail or notification received.
> 
> What is your configuration in Settings -> App Preferences?
> 
> It should look like this
> 
> ![image](https://private-user-images.githubusercontent.com/12009960/366434708-5d3138fd-3edf-429e-a363-08cc2b341db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTQxMTAsIm5iZiI6MTcyNjA1MzgxMCwicGF0aCI6Ii8xMjAwOTk2MC8zNjY0MzQ3MDgtNWQzMTM4ZmQtM2VkZi00MjllLWEzNjMtMDhjYzJiMzQxZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExMjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDg0MjMyYTQ0ZDhkMTk0NmQyYTFkYjhiYjRjNDgwN2M5ZGM4ODYyNjkzNTRiYjYzZTU3ZDQ3MWU2ZDlhNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HbdklQGL8kNzDk8lCWQOCWC53Fs_6mW5ZSOJxFycdKc)

Exactly like that... When Wino Mail is on system tray no email or notifications but when I open the emails pop ups but in system tray nothing.

**Comment by iamsaswatachakraborty** [comment]
I have just installed the latest version from Microsoft Store and setup everything correctly and it takes more than 2-3 minutes to get new emails (if not synced manually). Thunderbird in comparison takes only a couple of seconds to get emails.
