### ISSUE TITLE
[Suggestion] Package Tracking number monitor/scanner

### ISSUE THREAD

**Issue by duckduckdog** [bkaankose/Wino-Mail#28]
First let me say the app is looking great & I hope you can work out your problem with google!

I apologize that this isn't the correct place to ask, but I am trying to figure out why no Email client will scan your inbox for tracking numbers & populate some kind of package tracking & purchases window.

There are package tracking desktop apps, but no way to auto-populate them. There was a site that let you filter & forward emails from retailers, but that is a terrible privacy concern. It seems that an Email client is the only tool that can do this job, but none do.

I wish you success! Wino mail looks nice on my desktop. 

If you'll allow another suggestion, a filter to search out all the unsubscribe links from the email's in your inbox. Once every few months I houseclean & it would be awesome to see all the links in one place.

**Comment by bkaankose** [comment]
Thanks for the suggestions. However, a pure Mail client has not much to do specifically for package tracking. Simply it can't know what the situation with your Amazon order for example is. It can, but it's not Wino's job I think :) 

I understand the need to execute custom operations for different purposes though. Maybe Wino can offer a filtering mechanism & custom actions through some kind of scripting stuff later on, which will enable everybody to create their own system. Similar to Outlook policies. 

I have plans to integrate [list-unsubscribe](http://www.faqs.org/rfcs/rfc2369.html) header though which will show Unsubscribe button inside the application. However, I don't want to put this as a filtering type. It does not serve to general purpose of filtering mails unfortunately. What can be done is you may see an icon for the mails that you can unsubscribe from, and unsubscribe one by one.

**Comment by bkaankose** [comment]
Closing this issue as this is not relevant to Wino at the moment. I will create another enhancement request for unsubscribing from mails later on.
