### ISSUE TITLE
[Proposal] Add the Calendar section

### ISSUE THREAD

**Issue by P40L0X** [bkaankose/Wino-Mail#282]
I know Wino Mail born to replace the (ugly) new Outlook app with a better legacy of the old native "Mail & Calendar" app but the "Calendar" section is totally missing right now.

Please evaluate also adding it for future versions in order to have a proper successor of "Mail & Calendar" app.

Thank you,
-P

**Comment by bkaankose** [comment]
Calendar related topics are discussed in this discussion #85
