### ISSUE TITLE
[Proposal] Can you compile this for macOS please - thank you!

### ISSUE THREAD

**Issue by coopfidgets** [bkaankose/Wino-Mail#285]

**Comment by Tiktack** [comment]
Currently it uses UWP and there no way to compile it for MacOS.

**Comment by bkaankose** [comment]
Yeah unfortunately that's not possible :) However, if someone willing to port it for different operating systems, it's possible with MAUI or UNO with some effort.

Still requires tremendous effort to create UI, but synchronization and business logic is extracted in the code.

**Comment by bkaankose** [comment]
Closing the issue since it'll not be worked on.

**Comment by lextm** [comment]
Related to #869 and a cross-platform fork is coming.
