### ISSUE TITLE
[Bug] Handling GONE response for Outlook delta queries.

### ISSUE THREAD

**Issue by bkaankose** [bkaankose/Wino-Mail#290]
**Describe the bug**
Outlook synchronizer stores delta link with the token for each folder separately. These links expire after certain time if the user didn't synchronize for a while or just MS decides to expire the token. This results user to lose the client validity and app becomes unstable.

**Expected behavior**
410 gone response from delta queries must be handled gracefully.

**Additional context**
https://learn.microsoft.com/en-us/graph/delta-query-overview#synchronization-reset

**Comment by zkkzkk32312** [comment]
hi @bkaankose  
is the current workaround just to re-add the email account?
mine has been stuck for days.

**Comment by bkaankose** [comment]
> hi @bkaankose is the current workaround just to re-add the email account? mine has been stuck for days.

Unfortunately yes.
