### ISSUE TITLE
[Bug] Flagging does't work

### ISSUE THREAD

**Issue by zkkzkk32312** [bkaankose/Wino-Mail#297]
**Describe the bug**
After flagging an email, if you move to another inbox and come back, it shows it is not flagged

**Expected behavior**
the email is flagged and can be see when filtered by flagged status.

**Screenshots**
![image](https://github.com/user-attachments/assets/e0ce14ab-ad5a-4bd4-b21b-063386f87679)

**Additional context**
this was from my hotmail inbox, v1.7.8.0

**Comment by bkaankose** [comment]
Wino Mail reflects the UI changes first before sending the network request and re-synchronize quickly to receive changes from the API, and reflects changes again. Until the network call for re-synchronization finishes, no database changes are applied.

Are your mails always stucked as unflagged even after re-synchronization?

**Comment by zkkzkk32312** [comment]
> Wino Mail reflects the UI changes first before sending the network request and re-synchronize quickly to receive changes from the API, and reflects changes again. Until the network call for re-synchronization finishes, no database changes are applied.
> 
> Are your mails always stucked as unflagged even after re-synchronization?

yea pretty much,
unless I have to stay in the same inbox UI, wait till the network call to be synced (i'll test now),
otherwise it never worked on my end.

**Comment by zkkzkk32312** [comment]
> Wino Mail reflects the UI changes first before sending the network request and re-synchronize quickly to receive changes from the API, and reflects changes again. Until the network call for re-synchronization finishes, no database changes are applied.
> 
> Are your mails always stucked as unflagged even after re-synchronization?

ya the moment I switch inbox and comeback (waited), its no flagged.

**Comment by bkaankose** [comment]
This issue is fixed for the next release v.1.8.0.

1.8.0 is released to Beta channel. If you'd like to try that version please [go here](https://github.com/bkaankose/Wino-Mail/releases/tag/v1.8.0) and [follow the instructions here to install](https://learn.microsoft.com/en-us/windows/application-management/sideload-apps-in-windows) until it's released to Store.

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
