### ISSUE TITLE
[Bug] Signature image not displayed on web-based Gmail.

### ISSUE THREAD

**Issue by cutesniper22** [bkaankose/Wino-Mail#298]
**Describe the bug**
As per titled, the signature image is not displayed after sent via wino mail.

**Screenshots**
<img width="638" alt="image" src="https://github.com/user-attachments/assets/244486aa-3a58-41b3-b293-8441d0881949">

**Comment by Tiktack** [comment]
Fix will be included in next release. PR #313

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
