### ISSUE TITLE
Is Wino Mail abandoned?

### ISSUE THREAD

**Issue by Shomnipotence** [bkaankose/Wino-Mail#3]

**Comment by znbaboy** [comment]
Devs response to future updates: https://i.imgur.com/5cy5Df9.png

Devs response to opensource: https://i.imgur.com/mMZ29vW.png

This was 10 months ago...

**Comment by Shomnipotence** [comment]
> Devs response to future updates: https://i.imgur.com/5cy5Df9.png
> 
> Devs response to opensource: https://i.imgur.com/mMZ29vW.png
> 
> This was 10 months ago...

Yes I know but 10 months later……

**Comment by znbaboy** [comment]
> 

i dont know. im just giving you the last thing i heard you goofy

**Comment by bkaankose** [comment]
Sorry for the late response. I had my answers in the Discord channel yesterday about the delay :)

You can now download Wino Mail Preview from Microsoft Store.

https://www.microsoft.com/store/apps/9NCRCVJC50WL

You can check the latest updates on Wino development in this Discord channel

https://discord.com/channels/714581497222398064/932666402005987400
