### ISSUE TITLE
Some UI/UX Suggestions

### ISSUE THREAD

**Issue by ottozumkeller** [bkaankose/Wino-Mail#30]
First of all, I would like to say that Wino Mail is a really good alternative to the Windows Mail app and you do an extremely good job. Furthermore, I have a few suggestions for improvement regarding the user interface.

1. the rightmost menu section on my screen, when extended, is almost a quarter of the screen wide, leaving a lot of empty space (see image 1).

2. when the menu section is retracted, a Google logo is displayed in the remaining column. However, due to the central orientation and the height of the dropdown box, very far down (see image 2). I would prefer the Google logo to be directly below the + icon. Maybe by moving the logo to the top or by making the dropdown menu a smaller button.

3. in the email overview section, emails whose accounts don't have names are displayed without logo or sender name (see image 3). My solution would be to display the email address in such a case and at least a placeholder logo, e.g. a colored circle with the first letter of the email address (like in Gmail).

4. when the actual email is displayed, the content is displayed in a serif font. I would change this to a sans-serif font.

5. for the more distant future (when Wino Mail is more famous), translation into other languages would be desirable. This could be done relatively easily through the community with e.g. Crowdin.

Image 1
![Image 1](https://github.com/bkaankose/Wino-Mail/assets/94012287/78d71535-1871-4156-9bbb-8d9a765c72bc)

Image 2
![Image 2](https://github.com/bkaankose/Wino-Mail/assets/94012287/e6b0a624-42d5-40b7-af6e-7258838a263c)

Image 3
![Image 3](https://github.com/bkaankose/Wino-Mail/assets/94012287/19eeb65e-55e2-438f-bd8c-ed48cd4f49f3)

**Comment by bkaankose** [comment]
I created a separate issue for number 1 (#32) and number 3 (#33) for your list.

**Comment by bkaankose** [comment]
Localization support is implemented for the next version 1.7.0 which will be released in Februrary.

Other menu adjustments you suggested either partially implemented to satisfy the need in other bugfixes or can't be implemented without big changes on the underlying menu system Wino has.

Therefore I'll close this issue for now. If you'd like to discuss further, please open another issue.

Thanks!
