### ISSUE TITLE
[Proposal] Hide unread mails from Taskbar

### ISSUE THREAD

**Issue by brunossn** [bkaankose/Wino-Mail#300]
**Describe the solution you'd like**
I have a habit of leaving dozens of emails unread, to read later.

It would be great if there was a setting to hide the number of unread emails from the Windows TaskBar.

**Is your proposal implemented in Windows Mail?**
There is no option to disable it as Windows Mail never displays this information.

**Additional context**
![Captura de tela 2024-08-01 180346](https://github.com/user-attachments/assets/49347993-2b8e-47d2-a172-06962ffb3098)

**Comment by bkaankose** [comment]
Go to Manage Accounts -> Select account > Folder settings. There should be Notification Badge option. You can exclude specific folders from the calculation.

Give it a try and let me know if it works for you.

**Comment by brunossn** [comment]
This works in the folder list, but I want to hide all notifications only from taskbar.

**Comment by bkaankose** [comment]
What was I thinking... You are right. That option is for unread badge in the list. Let's keep this issue as an enhancement for now.

**Comment by wetpaint2000** [comment]
Yes, the option to limit number of emails displayes taskbar would be excellent. Also, an option for focused mail would also complete this excellent app.  Outlook is becoming ransomware!!!

**Comment by bkaankose** [comment]
![image](https://github.com/user-attachments/assets/6ba42e3d-bc67-40ce-991b-1ade3cf20de4)

Next version will have an option per-account to enable/disable this taskbar badge. If you disable all of your accounts, no badge count will be shown on the taskbar.

**Comment by bkaankose** [comment]
New version 1.9.40 is released yesterday that fixed this issue. Closing as fixed. You can find the new menu under Manage Accounts -> Account details to separate these.
