### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by senolfndk** [bkaankose/Wino-Mail#306]
Add Turkish language

**Comment by bkaankose** [comment]
Turkish language exists in Crowdin, but it's not translated yet. If you handle translating the strings I can enable Turkish for the next release.

https://crowdin.com/project/wino-mail/tr

**Comment by senolfndk** [comment]
I am not an expert on this subject.

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
