### ISSUE TITLE
Conversation View, Threading, Group by Conversation

### ISSUE THREAD

**Issue by victorjon68** [bkaankose/Wino-Mail#311]
Current Behavior: Emails that are replies to a previously sent email are automatically grouped into a thread or conversation view.
Desired Behavior: An option in the settings that allows users to disable the conversation view or threading, so each email appears individually in the inbox.

**Comment by Tiktack** [comment]
This setting already exists. Settings -> Message List -> Conversation Threading. Turn off it and every mail should be displayed individually. 
Closing this issue, since it's already implemented.

**Comment by victorjon68** [comment]
Thank you, I don't understand how I did not see it even after going through the settings multiple times.
