### ISSUE TITLE
[Proposal] Button to Relink Accounts Without Having to Delete Them First

### ISSUE THREAD

**Issue by RooRay** [bkaankose/Wino-Mail#312]
**Describe the solution you'd like**

It would be nice to have a feature, say under Manage Accounts > "Account Name" to be able to reconnect/relink the account without doing currently the only other option which is to delete it and add it again, which causes Wino Mail to resync every email for the account.

**Is your proposal implemented in Windows Mail?**

I'm not sure, I think it might've been but I can't say for sure

**Additional context**

Keep up the great work on Wino Mail, it's really good :)

**Comment by bkaankose** [comment]
You don't need to delete and re-add your account to unlink.

![image](https://github.com/user-attachments/assets/5093e76f-8e7a-4010-8d1c-d98ac7c703ec)

This page under Manage Accounts will allow you to add new accounts to link or remove accounts from it.

**Comment by bkaankose** [comment]
Closing the issue since it's already possible to edit existing linked accounts.
