### ISSUE TITLE
[Proposal] Automatic attachment saving

### ISSUE THREAD

**Issue by nsilveri** [bkaankose/Wino-Mail#315]
Hi, I'd like to propose a feature for automatic attachment saving:

It would be great if the client could automatically save received attachments to a specific folder (defined by the user) for each sender. Additionally, if possible (this might be a bit more complex), the attachments could be saved to a specific folder based on the context/content of the email. Let me give you an example:

There are emails from the bank that attach fixed monthly payments. I was thinking that, depending on the amount reported in the attached PDF (if the app can read the content), it could be possible to save the attachment in a specific folder.

**Comment by bkaankose** [comment]
Hello, this is not something that mail clients can or should do. App can't take action based on your personal content, it shouldn't do anyways.
