### ISSUE TITLE
[Proposal] Keep draft emails saved while being composed

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#320]
In the current behaviour of Wino Mail, a draft email is generated by: creating a new email, or replying/forwarding from an existing email. While the draft is being composed, clicking away from the draft (such as reading another email) and then back to the draft results in the following:
1. To/Cc/Bcc entries and the Subject are preserved.
2. The body of the email is reset. For new emails, this means it is empty. For reply/forward, it is reset to the content of the email being referenced. In both cases, it means any message that was being composed is lost.

Windows Mail's behaviour is to save and restore the full state of the draft, including the body. I suggest to implement this behaviour.

**Comment by bkaankose** [comment]
This is a regression bug. I am working on a fix. Will be merged to next beta release.

**Comment by bkaankose** [comment]
Fix is included in #324. I will create new beta release soon to test these changes.

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
