### ISSUE TITLE
[Proposal] Override folder name locally if the change cannot be synced

### ISSUE THREAD

**Issue by mrleblanc101** [bkaankose/Wino-Mail#322]
**Describe the solution you'd like**
Hi, I noticed that iCloud name the Inbox in all caps as "INBOX".
This looks out of place, so I tried renaming it "Inbox", but I got an error message saying the name change couldn't be synced.

I get that renaming the inbox is not allowed by iCloud probably for some legitimate technical reason, but I'd love if we could locally override the name in the app. 

Otherwise, I propose that the name should probably normalized. (lowercase the whole word and uppercase the first letter)

![Screenshot 2024-08-18 at 11 05 21 PM](https://github.com/user-attachments/assets/addd01e7-b094-4f5b-a05e-2a01393b4503)

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
