### ISSUE TITLE
[Bug] The preview for received emails displays sender name inccorectly

### ISSUE THREAD

**Issue by MilkTeaCat52** [bkaankose/Wino-Mail#327]
**Describe the bug**
The preview for received emails in the left pane sometimes shows the sender name incorrectly. The sender name is correct when the email is opened in the right pane. The incorrect name often contains "bounce". I've found that this bug mostly occurs for IMAPs.

**Expected behavior**
The sender preview should be the same as what is shown in the email body (the red box on the right pane in the screenshot).

**Screenshots**
![image](https://github.com/user-attachments/assets/d902702a-ddc4-4902-9e66-ffb09e406354)

**Additional context**

**Comment by bkaankose** [comment]
New version 1.9.40 is released yesterday that fixed this issue. Closing as fixed. Please comment if it didn't work for you.
