### ISSUE TITLE
[Bug] Conversation thread issues

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#338]
In v1.7.8 and v1.8.2, attempting to delete an entire conversation causes an error pop-up ("Synchronization Failed"). After this, for a short while the conversation is removed from the UI. In actuality, only some emails are deleted. It's unclear what determines which emails are deleted and which are not. After syncing, the emails which have not been deleted return.

In v1.8.5, the above bug is fixed, however a new bug has been introduced.
Left clicking on the conversation causes it to unfold when folded, or fold when unfolded. However, left clicking on any of the three buttons for that conversation (e.g. archive, delete, flag) also triggers this fold/unfold behaviour. So these buttons are now not functioning.

As a current workaround, right-clicking on a conversation to bring up menu options can be done instead.

**Comment by bkaankose** [comment]
#345 should address the issue with hover actions. Marking as fixed.

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
