### ISSUE TITLE
[Bug] Outlook account Deleted Items folder appears empty

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#340]
This bug is observed on v1.8.5. It affects Outlook accounts (not Gmail).

Navigating to the Deleted Items folder, the folder appears to be empty in the default view (i.e. when the "All" filter is selected). If an email is deleted, at the time it happens it will appear in Deleted Items, but then navigating away and back again will reset the view to empty.

If any filter is used, emails become visible. For example, filtering by a search string, or filtering by "Has files".

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
