### ISSUE TITLE
[Bug] Crash when switching between email accounts

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#349]
In Wino Mail, each email account has folders separated into two groups:
- Pinned folders, which are always visible
- Unpinned folders, which are revealed by expanding the "More" tab

To reproduce the crash:
1. Have at least 2 email accounts added to Wino Mail client
2. Expand the "More" tab and select an unpinned folder
3. Select the other email account. This should result in a small delay, then the client crashes.

Workaround is to always select a pinned folder before switching email accounts.

**Comment by horseshoe107** [comment]
Observed on v1.8.7

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
