### ISSUE TITLE
Licensing and Building from source

### ISSUE THREAD

**Issue by benswolo** [bkaankose/Wino-Mail#35]
Is this app open source? I'm interested in trying this app out but I feel reluctant about downloading something that could potentially track my credentials. Can I build this app from source?

**Comment by bkaankose** [comment]
Hello, app is not open sourced yet unfortunately. I have plans to do it in the future though.

Wino does not share any credentials outside of your local environment. All credentials are stored in your local sandboxed environment where other apps can't have access to. Both Microsoft and Google authentications are done through OAuth 2.0 (industry standard authorization protocol) with the SDKs that these companies provide.

I have also shared a privacy policy as well in application's website.

[Privacy Policy](https://www.winomail.app/privacy_policy.html)

**Comment by benswolo** [comment]
awesome. Please link the privacy policy in the microsoft store, the current privacy policy links to a 404 page on github

**Comment by IdkWhatToCallMe123** [comment]
+1 waiting for open source

**Comment by bkaankose** [comment]
Privacy policy URL has been updated in Microsoft Store page.

Closing the issue for now as 'not planned' about open-sourcing the project. I will update the Readme file with the plans I have about open sourcing it in the future.
