### ISSUE TITLE
[Bug] Attachments lost when sending an email from Outlook

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#350]
This bug was observed on v1.8.7 with an Outlook account. There was no issue with Gmail.

To reproduce the bug:
1. Select an outlook account and compose a new mail
2. Attach a file. This can be done via Insert->Files, or by drag-and-drop interface to the top of the composer window.
3. The attached file now appears in the composer UI under the Subject line
4. Send email. The email is sent, but any attachments are gone, both from the received email and the sent email.

**Comment by horseshoe107** [comment]
A related bug also seems to happen for Outlook account with image insertion, which I have described in a comment to #337

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.
