### ISSUE TITLE
[Bug] Cannot setup IMAP in v1.8.7

### ISSUE THREAD

**Issue by huouer** [bkaankose/Wino-Mail#352]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bkaankose** [comment]
Please give more details and share the logs... What is the server? What settings do u use?

**Comment by huouer** [comment]
how to get the logs?
![2024-09-06_180425](https://github.com/user-attachments/assets/4d604386-5381-415f-a7ee-7a640f59853d)
![2024-09-06_180624](https://github.com/user-attachments/assets/49386d8a-599a-464f-8f5a-2034da4a379e)

**Comment by bkaankose** [comment]
I see that you are trying to connect to Yahoo. You must generated an **app password** for that.

Please follow the guide here to generate one and use that password instead of your normal password.
https://help.yahoo.com/kb/SLN15241.html

Logs are under this folder. Replace username part with your computer's username.

C:\Users\**username**\AppData\Local\Packages\58272BurakKSE.WinoMailPreview_mhdqskaa8n2sj\LocalState\

**Comment by huouer** [comment]
I did setup and use the app password.

**Comment by huouer** [comment]
ImapProtocolLog.log has 0b

**Comment by huouer** [comment]
Same setting works in v1.7.8.0 (installed from Microsoft Store)

**Comment by huouer** [comment]
WINO automatically updated to 1.9.0 and stops me using yahoo IMAP. Same error.

**Comment by bkaankose** [comment]
I'll investigate the causes. Do you have some sort of network routing like a VPN or proxy on your machine? I can setup my Yahoo account without even going to advanced configuration.

![image](https://github.com/user-attachments/assets/565e6db1-0399-41b5-813c-44624b5eb635)

**Comment by shrugal** [comment]
No VPN or proxy for me, the server is in my local network.

**Comment by huouer** [comment]
> I'll investigate the causes. Do you have some sort of network routing like a VPN or proxy on your machine? I can setup my Yahoo account without even going to advanced configuration.
> 
> ![image](https://private-user-images.githubusercontent.com/12009960/367253058-565e6db1-0399-41b5-813c-44624b5eb635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzM0ODUsIm5iZiI6MTcyNjI3MzE4NSwicGF0aCI6Ii8xMjAwOTk2MC8zNjcyNTMwNTgtNTY1ZTZkYjEtMDM5OS00MWI1LTgxM2MtNDQ2MjRiNWViNjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAwMTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDJkYWE1NTJmNGQyMWU5MjhlZWQ3MGNmNzQzNzA2ZTlkZTQyODE2OTJiNjVkNmEyOTY0OTNmOGM1Y2U3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qdlmvrggbNDykVsOwSINWEJcaGATXvPGux3NOZRV70g)

You are right. Yahoo IMAP was blocked by my VPN. I can add Yahoo IMAP successfully in Wino 1.9.1.
