### ISSUE TITLE
[Bug] Mail content viewer restricted due to large number of recipients/attachment

### ISSUE THREAD

**Issue by cutesniper22** [bkaankose/Wino-Mail#356]
**Describe the bug**
(v1.8.7.0) As per titled, mail content viewer below difficult to be viewed when there're too many recipients/attachments 

**Expected behavior**
Wino Mail suppose auto hide them or provide button to expand recipients list if required.

**Screenshots**
<img width="552" alt="image" src="https://github.com/user-attachments/assets/20456114-6668-4018-b529-d468ffd934e3">

**Additional context**

**Comment by Tiktack** [comment]
Closing as duplicate #393
