### ISSUE TITLE
Can't add a gmail account in app

### ISSUE THREAD

**Issue by Juljina** [bkaankose/Wino-Mail#357]
**Describe the bug**
Can't add a gmail account in app

**Expected behavior**
Adding a account?

**Screenshots**
![image](https://github.com/user-attachments/assets/36af5820-d9b7-4982-a721-ac6e405a5216)
![image](https://github.com/user-attachments/assets/f2676d34-0a08-4936-a05a-edab186432b8)

**Additional context**
When I trying to add my gmail account, it's stuck at "initializing". Also all my accounts disappeared from app

**Comment by bkaankose** [comment]
Latest version 1.9.0 required re-adding of the accounts due to migration.

Gmail authentication is also moved to companion app, which does not activate the browser when OAuth is requested. Please check your browser for continuing authentication.

**Comment by Juljina** [comment]
What is the companion app

**Comment by bkaankose** [comment]
It's a separate application that handles synchronization for Wino Mail.

When see 'initializing' pop-up, your browser must be activated in the background with Gmail's authentication website. Continue authentication process for  Wino Mail in your browser.

**Comment by Juljina** [comment]
I'm sorry, I still don't understand how to add

**Comment by bkaankose** [comment]
> I'm sorry, I still don't understand how to add

1- Select Gmail from the account list in Wino Mail.
2- Click 'Create Account' (You will see that 'initializing' pop-up dialog.)
3- Your web browser (Google **Chrome**, Microsoft **Edge**, **Firefox** or **Opera** for example.) will be opened.
4- From the taskbar, switch to your web browser.
5- You will see that Google authentication web page is displayed.
6- Allow Wino Mail permissions and hit continue.

After these steps Wino Mail will be activated again and your account will be added.

**Comment by bkaankose** [comment]
I see you have Arc Browser as well along with Microsoft Edge. I assume what is happening is that Arc is taking the protocol activation Wino triggered and does not do anything about it.

Can you make sure that your default browser is set to Microsoft Edge and try again?

**Comment by Juljina** [comment]
On that video, Microsoft Edge was set as a default browser

**Comment by bkaankose** [comment]
This is a screenshot from the past in our Discord channel

![image](https://github.com/user-attachments/assets/ce6dee77-8ad0-4c8c-adab-9991c91ff12a)

**Comment by Juljina** [comment]
After changing default browser to Edge, nothi2g happen. It's still say "Initializing" and nothing is opening on edge

**Comment by Tiktack** [comment]
Can you please confirm that you have Edge as handler of http and https requests? Like on screenshot below:
<img width="821" alt="image" src="https://github.com/user-attachments/assets/0da55d16-230e-4a83-865a-07b79ad76fc1">

**Comment by Juljina** [comment]
![image](https://github.com/user-attachments/assets/c0e09276-8f14-40fc-9fe5-f5a86756d2e1)
Here

**Comment by Tiktack** [comment]
Another question. When you getting this "initializing" pop up, can you check your system tray? Is Wino Mail present there? 
![image](https://github.com/user-attachments/assets/7ce57d55-a308-4814-b8cc-e2bed782bec1)

**Comment by Juljina** [comment]
Yeah, it here
![image](https://github.com/user-attachments/assets/c00cb945-20c3-405b-b854-128baa177357)

**Comment by Nick-Ga** [comment]
I'm having exactly the same issues trying to add a hotmail account since the latest update. I've folowed all of the steps above, deleted the application and reinstalled it, but it never opens the browser ( currently set to Edge)

**Comment by bkaankose** [comment]
> I'm having exactly the same issues trying to add a hotmail account since the latest update. I've folowed all of the steps above, deleted the application and reinstalled it, but it never opens the browser ( currently set to Edge)

For Hotmail account you must select Outlook provider which uses different authentication method. It shouldn't open any browser for you.

**Comment by Nick-Ga** [comment]
I have done that and logged in with my account details - it then just hangs on Initilisation screen for around 10 minutes then says "account creation failed"
I've tried using th eprofile which is saved on the compter and also adding the email & password as a new account.
I've tried logging in by just pressing Next ( after entering the email and password) and also using the "Microsoft Apps Only" option.
After each attempt I get the initilizing screen for around 10 minutes then account creation failed
![Screenshot (2)](https://github.com/user-attachments/assets/45d7ac36-e6d1-4399-97fe-3f7ab4b37af2)
![Screenshot 2024-09-12 111157](https://github.com/user-attachments/assets/6f0a0b9a-a612-4b10-86ad-5ca498122ead)
![Screenshot 2024-09-12 112537](https://github.com/user-attachments/assets/50336f97-72ff-4e3b-9e12-13d9da21121d)
![Screenshot 2024-09-12 112609](https://github.com/user-attachments/assets/4f514581-c3be-412b-8b3a-927bdcd840d0)
![Screenshot 2024-09-12 112657](https://github.com/user-attachments/assets/00bb5a52-8ead-44e0-b9c8-0bc05da40e18)

**Comment by Nick-Ga** [comment]
The screenshots above are from a windows 11 pc, I'm currently trying the same thing on a different windows 10 pc with a clean install of Wino Mail

**Comment by bkaankose** [comment]
> I have done that and logged in with my account details - it then just hangs on Initilisation screen for around 10 minutes then says "account creation failed" I've tried using th eprofile which is saved on the compter and also adding the email & password as a new account. I've tried logging in by just pressing Next ( after entering the email and password) and also using the "Microsoft Apps Only" option. After each attempt I get the initilizing screen for around 10 minutes then account creation failed ![Screenshot (2)](https://private-user-images.githubusercontent.com/181342065/366834872-45d7ac36-e6d1-4399-97fe-3f7ab4b37af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzg3MzksIm5iZiI6MTcyNjEzODQzOSwicGF0aCI6Ii8xODEzNDIwNjUvMzY2ODM0ODcyLTQ1ZDdhYzM2LWU2ZDEtNDM5OS05N2ZlLTNmN2FiNGIzN2FmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTMzNmM2YzcwNDNiZmMyNTJiNzBkODEwMWUwOTVhOWU0NjVlNTEyZTYwYTU2ZTZlNWI1OTgxOWVjZWU0OWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A1zmubR5aY7ZSVbcNmr6oqIY5kr3WxIGMVChCGT7jQI) ![Screenshot 2024-09-12 111157](https://private-user-images.githubusercontent.com/181342065/366834878-6f0a0b9a-a612-4b10-86ad-5ca498122ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzg3MzksIm5iZiI6MTcyNjEzODQzOSwicGF0aCI6Ii8xODEzNDIwNjUvMzY2ODM0ODc4LTZmMGEwYjlhLWE2MTItNGIxMC04NmFkLTVjYTQ5ODEyMmVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmQyODc0ZGU2Mzk3OTM3NTU0YjIwOTMxNDQyNGFlNTYzYjg1NjRkNjg2MjlmNWM0YTk4NDg4MDZkMGNmNWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7jQCaM7ho7wjMdh1ktupYBzrpvnqnbGc177cg_o8MGA) ![Screenshot 2024-09-12 112537](https://private-user-images.githubusercontent.com/181342065/366834882-50336f97-72ff-4e3b-9e12-13d9da21121d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzg3MzksIm5iZiI6MTcyNjEzODQzOSwicGF0aCI6Ii8xODEzNDIwNjUvMzY2ODM0ODgyLTUwMzM2Zjk3LTcyZmYtNGUzYi05ZTEyLTEzZDlkYTIxMTIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2IxY2MyMzJmZjhmMGQ1NTVjM2JmYTM0YzJjNzAxNzZkZDI0Y2RmNmNmMjg5M2ZkOWZmNmVhYzRjYjRkZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SUPE48oa9IOLlw3OiUQ3EwNJTeEkhFG8Hx6WABiu7fs) ![Screenshot 2024-09-12 112609](https://private-user-images.githubusercontent.com/181342065/366834891-4f514581-c3be-412b-8b3a-927bdcd840d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzg3MzksIm5iZiI6MTcyNjEzODQzOSwicGF0aCI6Ii8xODEzNDIwNjUvMzY2ODM0ODkxLTRmNTE0NTgxLWMzYmUtNDEyYi04YjNhLTkyN2JkY2Q4NDBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjNjM2MzNTM4NmM4MDZkYzU0MGM2ZDUxZTYxN2IyMDdkYmQ2OGRlMGZlMjI4ODI1OTRjNzMwOGZiYzc0YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAevdlakaUEjbfO1BcKBc6LNWhL3YTpk499OkvXot1k) ![Screenshot 2024-09-12 112657](https://private-user-images.githubusercontent.com/181342065/366834896-00bb5a52-8ead-44e0-b9c8-0bc05da40e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzg3MzksIm5iZiI6MTcyNjEzODQzOSwicGF0aCI6Ii8xODEzNDIwNjUvMzY2ODM0ODk2LTAwYmI1YTUyLThlYWQtNDRlMC1iOWM4LTBiYzA1ZGE0MGUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDExNzE2YTRlNzg2NmI5MzFkNDY2ZGMyNmNjNzRjMmZjNmE2YTRiZDEyNTI1OGNmM2U0M2U5MzRkNmU5ZWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6LEofUVMJ8obHvpsc57Adk6CsbQ1TGCnX9Oj3eERZGo)

Are you sure that you are on the latest version (**1.9.1.0**) on Windows 11 machine? Looks like you are still using the old authentication mechanism (Web Authentication Broker) instead of new one (Web Account Manager).

**Comment by Nick-Ga** [comment]
Yep, it's definitely the latest version
![Screenshot 2024-09-12 120409](https://github.com/user-attachments/assets/789a4bf8-f2d1-4eb8-ba58-8f30f0e28f82)

**Comment by Nick-Ga** [comment]
The machine is also fully iup to date as far as Windows Update is concerned

**Comment by Nick-Ga** [comment]
I have just deleted all saved credentials in Credential Manager, rebooted the computer and tried again and it has sucessfully added the account. 
I'm not sure what changed but thanks for your help

**Comment by AmirMohammadAhmadi1384** [comment]
![Screenshot 2024-09-13 143637](https://github.com/user-attachments/assets/2fbd2a62-751e-4a69-bfe9-21a1b78bb2cf)
![Screenshot 2024-09-13 143723](https://github.com/user-attachments/assets/032ba3f2-30a4-40eb-b3d2-897cdfc12d83)
Help! i have the same problem but with Gmail and i use edge as my primary browser.

**Comment by bkaankose** [comment]
> ![Screenshot 2024-09-13 143637](https://private-user-images.githubusercontent.com/176696845/367268943-2fbd2a62-751e-4a69-bfe9-21a1b78bb2cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTM2MzcsIm5iZiI6MTcyNjI1MzMzNywicGF0aCI6Ii8xNzY2OTY4NDUvMzY3MjY4OTQzLTJmYmQyYTYyLTc1MWUtNGE2OS1iZmU5LTIxYTFiNzhiYjJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxODQ4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDk3NTI4NmRiMmY5NDI3YzI1Y2M4ODBiZTgwYjYzNzgzNThiM2RiZmU5OTQ3YmZmYWU4NWMyMzE5MWIxMmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XDJMxlaCYAJ87Dabthr8lHDBAG_17r2f-TfTMIuG-RY) ![Screenshot 2024-09-13 143723](https://private-user-images.githubusercontent.com/176696845/367268953-032ba3f2-30a4-40eb-b3d2-897cdfc12d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTM2MzcsIm5iZiI6MTcyNjI1MzMzNywicGF0aCI6Ii8xNzY2OTY4NDUvMzY3MjY4OTUzLTAzMmJhM2YyLTMwYTQtNDBlYi1iM2QyLTg5N2NkZmMxMmQ4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxODQ4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDQ0YTg4NzEyMTcyYWM2M2ZkMWUwNDIxMzNmN2MyNGZmMDE0ZjAwMDUwNzhlYzEwOTg3YzVkZjZhNzc4YTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2MEBAA_IKDo94u7vqNGEblDK2JzjAIIO1HD8F8Lqhlc) Help! i have the same problem but with Gmail and i use edge as my primary browser.

Make sure to check all boxes in authentication page.

![image](https://github.com/user-attachments/assets/ef1e919e-53d6-4186-9433-3fe522049bc8)

**Comment by AmirMohammadAhmadi1384** [comment]
I checked all the boxes but still did not work.

**Comment by AmirMohammadAhmadi1384** [comment]
Can anyone Help me?

**Comment by bkaankose** [comment]
> Can anyone Help me?

Could you please e-mail logs to bkaankose@outlook.com? You can get the logs at Settings -> About -> Diagnostics -> Share Logs.

**Comment by bkaankose** [comment]
> **Describe the bug** Can't add a gmail account in app
> 
> **Expected behavior** Adding a account?
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/157807691/365945098-36af5820-d9b7-4982-a721-ac6e405a5216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTU1NTUsIm5iZiI6MTcyNjUxNTI1NSwicGF0aCI6Ii8xNTc4MDc2OTEvMzY1OTQ1MDk4LTM2YWY1ODIwLWQ5YjctNDk4Mi1hNzIxLWFjNmU0MDVhNTIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxOTM0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2UyZjU5YTQ2OTNkZDJkNjlmNzI5YWIzMDI4ZDZkMGNjZDRhYTM1OTRjMGY3Yzk0NWFkNDE2MGI2YWYyYTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ELyjpbijm7VzpiszjCet9CuHdQhvjLPsH7U_CNhFNZI) ![image](https://private-user-images.githubusercontent.com/157807691/365945108-f2676d34-0a08-4936-a05a-edab186432b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTU1NTUsIm5iZiI6MTcyNjUxNTI1NSwicGF0aCI6Ii8xNTc4MDc2OTEvMzY1OTQ1MTA4LWYyNjc2ZDM0LTBhMDgtNDkzNi1hMDVhLWVkYWIxODY0MzJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxOTM0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWIyMWZlODVhNjVkMTAwZjQ0NTg4MzBmY2UzMzdmZjNmYTRkMmYyMTM5NjkxMzRkYWU0MjM4MzA3YjczMGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zDS2w1Ouw4OsS2jPXLTrkl7IbloJhg7qZ2hrCxkk3pk)
> 
> **Additional context** When I trying to add my gmail account, it's stuck at "initializing". Also all my accounts disappeared from app

Regarding this problem, today I version 1.9.2.0 is published to Store. In the case of browser is not launched during authentication, you'll see a popup on the "initializing" popup to copy the authentication URL to navigate yourself. You can click 'copy' to copy authentication URL and paste it to your own browser.

**Comment by AmirMohammadAhmadi1384** [comment]
it is launching but when I select my account the error that says (account creation failed) comes out.

**Comment by AmirMohammadAhmadi1384** [comment]
ok i will share the logs

**Comment by AmirMohammadAhmadi1384** [comment]
I sent you the logs.

**Comment by AmirMohammadAhmadi1384** [comment]
> > Can anyone Help me?
> 
> Could you please e-mail logs to [bkaankose@outlook.com](mailto:bkaankose@outlook.com)? You can get the logs at Settings -> About -> Diagnostics -> Share Logs.

I sent you the logs.

**Comment by bkaankose** [comment]
> I sent you the logs.

![image](https://github.com/user-attachments/assets/878fd141-ddd1-42da-9455-75c1af9e6ba5)

This is the error you get. That's interesting. Can you please go to your Gmail profile settings (top right profile picture > click and go to 'manage account'), in Security tab on the left, click 3rd party apps details

![image](https://github.com/user-attachments/assets/3dedf034-f77b-49c3-b214-39bbfbdf4183)

Revoke all permissions you have given to Wino Mail and try again. This is the ideal page you should see when you go to details of the permission

![image](https://github.com/user-attachments/assets/344be2ef-ca7d-4563-83fe-fdf3562ab7d8)

**Comment by AmirMohammadAhmadi1384** [comment]
> > I sent you the logs.
> 
> ![image](https://private-user-images.githubusercontent.com/12009960/367911268-878fd141-ddd1-42da-9455-75c1af9e6ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTY5OTEsIm5iZiI6MTcyNjUxNjY5MSwicGF0aCI6Ii8xMjAwOTk2MC8zNjc5MTEyNjgtODc4ZmQxNDEtZGRkMS00MmRhLTk0NTUtNzVjMWFmOWU2YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE5NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxM2IxYTYyZWIyMWI5YjczMzcyZThkNWVmNmViYmQ2MmRkZjAwODQ4MGMxY2U0NDI2M2FhMTdkYjI1MjU0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqJjQbsHWbKD1hLPfz4atyjfc1CX8ecdANkRLJd-tJs)
> 
> This is the error you get. That's interesting. Can you please go to your Gmail profile settings (top right profile picture > click and go to 'manage account'), in Security tab on the left, click 3rd party apps details
> 
> ![image](https://private-user-images.githubusercontent.com/12009960/367912081-3dedf034-f77b-49c3-b214-39bbfbdf4183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTY5OTEsIm5iZiI6MTcyNjUxNjY5MSwicGF0aCI6Ii8xMjAwOTk2MC8zNjc5MTIwODEtM2RlZGYwMzQtZjc3Yi00OWMzLWIyMTQtMzliYmZiZGY0MTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE5NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMzk4OTI4YmUwMmIwOGM5ZGE2ZmE0ZTMwMDk4Y2MyZGY4MmUyMzM3NWQwMmI0N2UxMmM0ZWUxMGIwM2ZlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTNlrWMWk3mtwhTJ-GIQfwJxOl5aiKCRoSHif17khXE)
> 
> Revoke all permissions you have given to Wino Mail and try again. This is the ideal page you should see when you go to details of the permission
> 
> ![image](https://private-user-images.githubusercontent.com/12009960/367912309-344be2ef-ca7d-4563-83fe-fdf3562ab7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTY5OTEsIm5iZiI6MTcyNjUxNjY5MSwicGF0aCI6Ii8xMjAwOTk2MC8zNjc5MTIzMDktMzQ0YmUyZWYtY2E3ZC00NTYzLTgzZmUtZmRmMzU2MmFiN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE5NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYTNkMzY5N2Y1NzI5OGQwMzUxMTEyNzc3ZjM1ZTAyNDQyYTMxYzVkZTUzN2ZiNDllODg2MWNmMWFmM2NjNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EFUQyqTsQ6H9ZRDfMrTtogZ0Msa8mSnGNIEXbcbjxps)

it didn't work.

**Comment by AmirMohammadAhmadi1384** [comment]
It worked, i used a vpn.

**Comment by AmirMohammadAhmadi1384** [comment]
it looked like that the gmail cannot respond to the app because of restriction and that's weird because i didn't any problem on other Mail app!

**Comment by bkaankose** [comment]
Closing this issue since ability to copy authentication URL is implemented in 1.9.2.0 this week.

If you still can't authenticate with Gmail re-open the issue.
Thanks.
