### ISSUE TITLE
Forwarding not sending attachments

### ISSUE THREAD

**Issue by GreenDragon527** [bkaankose/Wino-Mail#36]
Forwarding emails with attachments doesn't appear to have the option to send the attachments on the original email, without downloading and reinserting them into the forward.

**Comment by bkaankose** [comment]
Thank you for the report. 

Attachments for composing mails were not developed before. In the next release (1.6.5, will be released in November) attachments are completed and I tackled this bug.

Labeling the issue as fixed for now.

**Comment by bkaankose** [comment]
Version 1.6.5 is now live on Microsoft Store. Closing this issue as it's been addressed. Please check it out and let me know if you encounter the issue still.
