### ISSUE TITLE
[Bug] Cannot add microsoft exchange/work email account

### ISSUE THREAD

**Issue by yuezhenglingluan** [bkaankose/Wino-Mail#361]
**Describe the bug**
After choosing Outlook, choose my work account, it says this:
![image](https://github.com/user-attachments/assets/f6ddab99-b0af-45f2-a7d6-d3a4688ead1a)

**Expected behavior**
it should sign in correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/a63cfbc4-c1ca-416b-893e-d7f316515585)

**Comment by bkaankose** [comment]
Office 365 accounts are officially not supported. Is it your own domain?

**Comment by yuezhenglingluan** [comment]
It is my own domain, and it works fine if I add it as outlook account before this update tho (thus why I made this issue)

**Comment by bkaankose** [comment]
I understand. Profile synchronization works different for Outlook and Office 365 accounts but they use the same synchronizer under the hood. That's why it's failing right now.

I will try to take care of the issue on the next update. Thanks for the feedback.

**Comment by bkaankose** [comment]
New release 1.9.1.0 is released to Store today which should fix this issue. You may not see your profile picture, but it will work at least.

Please test with the new version and re-open the issue if still exists.

**Comment by yuezhenglingluan** [comment]
I am sad to say, but the issue still occurs on my end when I try to add the exchange account with the same error after the update

**Comment by bkaankose** [comment]
> I am sad to say, but the issue still occurs on my end when I try to add the exchange account with the same error after the update
> 
> Also I have no idea how to reopen the issue since on github web I cannot find the button to reopen the issue

Is it possible for you to create test account for me to connect to your domain? I tried to setup a free Office 365 developer sandbox but wasn't successful. If there'll be cost for you, I will look for alternative options to give this a try.

**Comment by yuezhenglingluan** [comment]
I sent you an email to the outlook account in your profile with the test account information, the email will be from ling.yz@outlook.com

**Comment by zno3** [comment]
I also had similar problem on microsoft account on my windows but mine are stuck forever on initializing

**Comment by zno3** [comment]
> I also had similar problem on microsoft account on my windows but mine are stuck forever on initializing

it appears my kaspersky anti virus mark winoserver as malicious, even after i add to exclusion the app able to ran but still unable to add microsoft account, after i uninstall kaspersky it add microsoft account successfully

**Comment by chenseanxy** [comment]
I encountered the same issue here after the update. Could it be this?

https://github.com/bkaankose/Wino-Mail/blob/e897182b2347714fd044853b400f505408086c79/Wino.Core/Synchronizers/OutlookSynchronizer.cs#L531-L540

Not sure if `Users["me"]` actually fits the `GET /users/{id | userPrincipalName}` parameters here, and Graph might just assume you're querying a non-existent ID (which by default should raise a `Not found`, but some larger orgs could forbid users from listing all users in the org)

https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=csharp

**Comment by chenseanxy** [comment]
Seems so! This at least fixed this issue for my org

<img width="269" alt="image" src="https://github.com/user-attachments/assets/3cd1fe45-ca6c-4b09-b043-163dce5df62b">

**Comment by chenseanxy** [comment]
Please try updating to the latest version. This had made it to release thanks to @bkaankose
