### ISSUE TITLE
[Bug] IMAP connection failed: Socket access forbidden

### ISSUE THREAD

**Issue by shrugal** [bkaankose/Wino-Mail#376]
**Describe the bug**
Since Wino Mail updated to 1.9.0 I cannot add my IMAP/SMTP email account anymore. When I try I get the following error message:

> Connection Failed
> An attempt was made to access a socket in a way forbidden by its access permissions [Server IP]:993

The server is selfhosted and located in the local network. It worked fine before 1.9.0, and it still works without problem with other email clients on the same PC or on my phone and tablet.

I'm not using any proxy or VPN, just a wired LAN connection.

**Expected behavior**
It should successfully add the account and load mails.

**Screenshots**

![wino-2](https://github.com/user-attachments/assets/24701e35-828e-43b4-bcb2-625a2992b162)

**Additional context**
Issue #352 with the same error message was closed yesterday, but that one involved Yahoo and a VPN connection.

Maybe of note is that the mail account I added before 1.9.0 was gone after the update, that's why I'm trying to add it again.

**Comment by bkaankose** [comment]
App tries to connect/authenticate to the server for validation before creating the account. This validation is not done by the Wino Server, but the actual UWP application, which is working in sandboxed environment that has no access to localhost.

#381 moves this validation to server, which can do it without being blocked by the system. I think this will fix your issue. Labeling as fixed for now, will let you know when next version 1.9.2.0 hits the Store.

**Comment by bkaankose** [comment]
1.9.2 went live today. Could you please try again with the never version?

**Comment by shrugal** [comment]
It works again, ty! :D

One minor thing I noticed: The IMAP and SMTP ports where no longer filled out by default.
