### ISSUE TITLE
[Suggestion] Make Delete Key delete the current Mail

### ISSUE THREAD

**Issue by aless2003** [bkaankose/Wino-Mail#38]
I'm rarely lifting my hands of my keyboard if I don't have to, but as far as I could tell there's no way to delete Mails via the keyboard. Therefor I would like to ask if it would be possible to make the "DEL" key on the keyboard delete the currently selected mail. This has been something I'm used to have in pretty much every mail app I ever used and I think it would by quite nice to have it

**Comment by bkaankose** [comment]
This is indeed an issue and must be addressed.

Overall, touch interactions like swipe to delete etc. must be implemented as well. I haven't done a lot UX implementation so far but this seems like higher priority.

**Comment by bkaankose** [comment]
This issue is fixed in the next upcoming version in November. I will close the issue once the new version is published.

Thank you for the suggestion!

**Comment by aless2003** [comment]
Cool, thank you very much 😊

**Comment by bkaankose** [comment]
Version 1.6.5 is now live on Microsoft Store. Closing this issue as it's been addressed. Please check it out and let me know if you encounter the issue still.
