### ISSUE TITLE
[Bug] App doesn't stay closed

### ISSUE THREAD

**Issue by Coffeeling** [bkaankose/Wino-Mail#380]
**Describe the bug**
Set Wino Mail to terminate on close. Close Wino. Soon enough you'll have the Wino icon in the systray and Wino delivering email notifications.

**Expected behavior**
Wino Mail actually closes and doesn't run

**Comment by bkaankose** [comment]
1.9.2 went live today. Can you please update and confirm the fix?

**Comment by Coffeeling** [comment]
The fix seems to work.
