### ISSUE TITLE
[Bug]Crash on Opening Certain Emails

### ISSUE THREAD

**Issue by Mandoon14** [bkaankose/Wino-Mail#382]
Hi everyone, I have an issue with wino mail (which I love). Since I got the app, which was a while back now. I have and still am unable to open Royal Mail emails for eBay items, be it whether they have been posted or have arrived, since once clicked it just crashes. I have included a video to demonstrate. Please can you fix this if possible, as soon as you can. And thank you for the hard, ongoing work. An added note is that this is for a second Gmail account. Not my primary.

https://github.com/user-attachments/assets/62c9c2ca-ece5-44f3-8f43-e34766ff95c7

**Expected behavior**
For the email to just open normally.

**Screenshots**
https://github.com/user-attachments/assets/62c9c2ca-ece5-44f3-8f43-e34766ff95c7

**Additional context**
I still continue to use the app, but to view those emails I must use other software, which is turning me away from Wino-Mail. I don't want that to happen, so please fix it as soon as you are able/if you are able. Thank you so much and God Bless.

**Comment by bkaankose** [comment]
This should be fixed with 1.9.3.0 which was released a few days ago. Closing as fixed. Please re-open if you still encounter this issue.
