### ISSUE TITLE
[Suggestion] show folders in minimized side bar

### ISSUE THREAD

**Issue by AkazaRenn** [bkaankose/Wino-Mail#39]
First of all, thank you for your work! Definitely love the email app, especially under this time when Microsoft themselves are giving up on the UWP email app.

I would like to ask if it's possible that when we are running with **only one account**, the folders are shown on the minimized side bar, so we can click them even when the side bar is minimized?

I'm working on my 13-inch laptop mostly, which has a very limited screen space. It would be a nice adjust to give more space to the email contents without sacrificing any functionalities. Here's a demo how it may look like with a Gmail account:

<img width="960" alt="Screenshot 2023-10-12 095458" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/f87111c8-1eb4-45de-9f92-e4ed0187de04">

Thank you again!

**Comment by bkaankose** [comment]
Thanks for the review. Glad you liked Wino so far :)

I think this is a good enhancement that can be toggled in Settings later on. I'll put it into my backlog.

**Comment by bkaankose** [comment]
Closing this one since the new menu layout is implemented.
