### ISSUE TITLE
[Bug] Clicking on an attachment in draft removed it

### ISSUE THREAD

**Issue by lostmsu** [bkaankose/Wino-Mail#398]
**Describe the bug**
I clicked an attachment in draft, and it just got removed.

**Expected behavior**
The attachment should get opened.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7d72fd1-a58f-41b0-b5cf-3a062a4077e0)

Me just before clicking at that exact spot.

**Additional context**
Main branch from yesterday, commit 67828365ca85c8ee1680a07a93d4fbf16507b293

**Comment by bkaankose** [comment]
This didn't make it to the recent build, but I'd like to improve this part as well.

When you attach a file to composer, it's loaded into memory. You can as well delete the physical file from the disk and Wino can still send the attachment. Therefore opening the file for preview requires content to be saved to temporary folder in case of the file is deleted.

I'll have it implemented for the next version.

**Comment by lostmsu** [comment]
There's also the issue that this particular area of the "button" activated the delete action instead of the open action.

**Comment by bkaankose** [comment]
New version 1.9.40 tries to mimic the same behavior as in WMC. Now clicking attachments should open them, there is a separate delete button on the side and right click offers Open/Save.

![image](https://github.com/user-attachments/assets/62ef25e6-d4ff-4784-a47d-4cd8d6645b38)
