### ISSUE TITLE
Wino-Mail app certificate expired

### ISSUE THREAD

**Issue by foursplaysroblox** [bkaankose/Wino-Mail#4]
Hello i wanted to install wino mail but it said the certificate is expired

**Comment by foursplaysroblox** [comment]
?

**Comment by foursplaysroblox** [comment]
How do i get a certificate that is not expired?

**Comment by bkaankose** [comment]
You can now download Wino Mail Preview from Microsoft Store.

https://www.microsoft.com/store/apps/9NCRCVJC50WL
