### ISSUE TITLE
[Suggestion] Drag and Drop functionality

### ISSUE THREAD

**Issue by minecreeper313** [bkaankose/Wino-Mail#41]
Maybe it's already planned and just not implemented yet, but I'd love to be able to just drag and drop my e-mails (for example into the deleted items section or into a folder for organisation purposes).
Relying on buttons is too inconvenient.

Amazing app by the way, looking forward to future updates!

**Comment by bkaankose** [comment]
Thanks for the review!

It's definitely needed. I have some underlying work done for drag & drop in the app, but "Move" functionality is not integrated yet in the synchronizers for both mail providers.

I am working on imap/smtp support at the moment. Therefore can't say about the next release for "Move" but it'll definitely be there soon.

**Comment by bkaankose** [comment]
I couldn't wait and just implemented Move functionality for all synchronizers, including unreleased IMAP accounts for the next version.

Labeling the issue as fixed for now. I will close it once the new version goes live in November.
Thank you!

**Comment by minecreeper313** [comment]
I'm glad to hear it! Looking forward to the new version and more.
Thank you and keep up the amazing work!

**Comment by bkaankose** [comment]
Version 1.6.5 is now live on Microsoft Store. Closing this issue as it's been addressed. Please check it out and let me know if you encounter the issue still.

**Comment by minecreeper313** [comment]
The new feature seems to work nicely! Keep up the great work
