### ISSUE TITLE
[Bug] mailto:// protocol ignores line breaks

### ISSUE THREAD

**Issue by marticliment** [bkaankose/Wino-Mail#414]
**Describe the bug**
When using mailto:// protocols, such as the following one `mailto:test@test.com?subject=TEST%20SUBJECT&body=Test%20Body%0AWith%20a%20line%20break`, the line break (character `%0A`) is ignored.
Windows Mail and Calendar app used to maintain the line breaks.

**Expected behavior**
This is how thst URL opens on Windows Mail
![image](https://github.com/user-attachments/assets/8efd728e-a5d9-47a1-8003-1be1c57f72d2)

**Current behaviour**
This is how it looks on Wino mail:
![image](https://github.com/user-attachments/assets/7d8cd6ee-16e5-4fda-8bec-92ec34b50105)

**Additional context**
This is very frustrating when using prebuilt mailto:// URLs, that are used to accelerate workflows. However, having to manually add the line breaks again is a pain and a loss of time.

Thanks for the great app!

**Comment by bkaankose** [comment]
New version 1.9.40 is released yesterday that fixed this issue. Closing as fixed. Please comment if it didn't work for you.

**Comment by marticliment** [comment]
It works now, thanks!
