### ISSUE TITLE
[Bug] Reading pane stays scrolled down when opening next e-mail

### ISSUE THREAD

**Issue by blablabla123455** [bkaankose/Wino-Mail#422]
**Describe the bug**
When I open an e-mail that is long enough to be scrolled, scroll down to the bottom of it and then click to open another e-mail that is long enough to be scrolled, that another e-mail is already scrolled to the bottom when viewed and I have to scroll to the top to see the beginning of it.

**Expected behavior**
Each opened e-mail is viewed from from top, not scrolled away from the top.

**Comment by bkaankose** [comment]
New version 1.9.40 is released yesterday that fixed this issue. Closing as fixed. Please comment if it didn't work for you.
