### ISSUE TITLE
[Custom IMAP/SMTP server] syncing and sending/receiving with iCloud not working. 

### ISSUE THREAD

**Issue by dudijd** [bkaankose/Wino-Mail#43]
I successfully added an account with my iCloud credentials, but nothing is syncing (windows stock mail app is syncing normally). 

![4WrH9OGy3f](https://github.com/bkaankose/Wino-Mail/assets/61502547/33bbc3b3-9cb2-4a83-bf06-91848b5fd2b5)

![image](https://github.com/bkaankose/Wino-Mail/assets/61502547/aa79268b-cf6a-41e3-a942-ef6b9a691fc3)

**Comment by bkaankose** [comment]
Thank you for the report. I have created a new iCloud account and tested this. It's indeed a bug with QRESYNC extension.

I will release a hotfix version that disables this enhancement for now until it's fixed properly in Wino.

**Comment by bkaankose** [comment]
Hotfix version 1.6.6 is pushed to Microsoft Store. It's expected to be published in couple hours. Labeling this issue as fixed for now. I can close it after your confirmation when the new version goes live @dudijd

**Comment by dudijd** [comment]
I can confirm that it works now (but I had to delete and add the account again).

**Comment by bkaankose** [comment]
Glad that finally it's resolved. Closing the issue.
