### ISSUE TITLE
[Bug] Language of Dates in Message-List always English

### ISSUE THREAD

**Issue by Achim16** [bkaankose/Wino-Mail#434]
Despite of having changed Settings->Display Language to a language other than English, 
the Dates in the message list are still shown in English , eg 'Saturday, October 12, 2024'.

Cheecked that no regional setting in Windows is set to English

Win10, 22H2, b5011.

**Comment by Tiktack** [comment]
Hi, currently dates are not translated. 
Particular issue was reported already and we can track it here #362
Closing as duplicate
