### ISSUE TITLE
[Proposal]

### ISSUE THREAD

**Issue by Xavi3RElvis** [bkaankose/Wino-Mail#439]
Would like to have the option to remove separation between focused and other same as outlook does for microsoft mail accounts.
Currently there is no way to remove the focused split

It is currently an option in outlook to not use focused

**Comment by bkaankose** [comment]
It's available for Microsoft accounts. 

Go to Manage Accounts > Account name. Disable this setting and restart the application.

![image](https://github.com/user-attachments/assets/3ac4b082-bf79-49d8-9607-66f0346a8934)

Restarting issue will be fixed for the next version.

**Comment by Xavi3RElvis** [comment]
Apologies and thank you, completely missed that section as I was looking for it in the app settings
