### ISSUE TITLE
[Bug] Can't see which mail without subject is unread

### ISSUE THREAD

**Issue by blablabla123455** [bkaankose/Wino-Mail#440]
**Describe the bug**
Mails without subject have empty line and because subject line informs user whether mail unread by changed color and bolded font, without it you can't tell quickly which one is unread (you have to filter by Unread to see them).

**Expected behavior**
Windows Mail was giving mails without subject an arbitrary one: `(No subject)`, so you could see it as unread if needed.

**Comment by bkaankose** [comment]
1.9.40 went live that fixes this issue. Closing as fixed.
