### ISSUE TITLE
Printing an email - possible?

### ISSUE THREAD

**Issue by Millanu** [bkaankose/Wino-Mail#446]
Just installed Wino as Outlook (New) is driving me nuts. All good so far but I cannot see any option to print my email. Is this possible or am I being stupid and not seeing it?

Thanks

**Comment by shhada** [comment]
i'm having this same issue. i can see there's functionality written for it if i search through this repository, but sadly no print button to be found on the installed program itself

**Comment by bkaankose** [comment]
I will have it implemented for the next release. I have never printed an e-mail before, but looks like this is one of the top requested features for Wino.

**Comment by bkaankose** [comment]
PR is merged. #471 

I will merge couple more things and ideally send a new version to Microsoft Store in 2 days.

Labeling as fixed.

**Comment by Millanu** [comment]
Good job 👍

On 9 November 2024 18:19:23 GMT, "Burak Kaan Köse" ***@***.***> wrote:
>
>PR is merged. #471 
>
>I will merge couple more things and ideally send a new version to Microsoft Store in 2 days.
>
>Labeling as fixed.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bkaankose/Wino-Mail/issues/446#issuecomment-2466387902
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***&gt;

J Matthews

**Comment by scrufdawg** [comment]
Seeing as how it's December 20 and there still isn't a print button, why mark this as fixed?

**Comment by bkaankose** [comment]
> Seeing as how it's December 20 and there still isn't a print button, why mark this as fixed?

We push fixes to main branch and label the issues that are handled as 'fixed'. Once the update goes to Microsoft Store, issues are closed.

Yesterday I have pushed an update (v1.9.40) to the Store which has the printing functionality. I will close the issue once it's published.

**Comment by bkaankose** [comment]
New update is live in Microsoft Store. Printing is on this menu.

![image](https://github.com/user-attachments/assets/872657d5-aa28-43ba-826d-716a13185f7b)

Closing as resolved.
