### ISSUE TITLE
[Bug] Gmail authentication does not work after a period of being offline

### ISSUE THREAD

**Issue by lostmsu** [bkaankose/Wino-Mail#447]
**Describe the bug**
After a couple of days of PC being off, Gmail won't synchronize.

**Expected behavior**
When Gmail token expires it has to be refreshed.

**Additional context**
Happens because `IsExpired` returns `false`, but Gmail refuses the token.

It could be this issue: https://github.com/praeclarum/sqlite-net/issues/217 (I'm in UTC-7)
Basically to correctly preserve timezone (UTC in this case) when storing timestamp in SQLite-net one must use [DateTimeOffset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=net-8.0). Although I tried a roundtrip, and the comparison with incorrect kind seems to work correctly.

But actually since there's `GmailClientMessageHandler` it could check the return code, and force token regeneration on Unauthorized (I would suggest to only do it once per request). Should be doable by adding response handler with `messageHandler.AddUnsuccessfulResponseHandler(new ...());` in `GmailSynchronizer` constructor.

**Comment by bkaankose** [comment]
Wino used to handle gmail tokens, but for the next update they'll be managed by Google auth library.

**Comment by bkaankose** [comment]
1.9.40 leverages Google .NET SDK for authentication going forward. That should fix the issue. Closing as fixed. We can come back if those issues are still happening in the future.
