### ISSUE TITLE
Open linked files before sending them

### ISSUE THREAD

**Issue by Cakti-Cactus** [bkaankose/Wino-Mail#458]
On the original mail app, when writing an email, it is possible to open attached files before sending them. It's quite convenient to verify we're about to send the correct file.

**Is your proposal implemented in Windows Mail?**
The proposal is implemented in the original app as shown below.
Possibility to open the file (or save it) either by right clicking on it or by hovering on the file's name.
Remove it by clicking on the x icon.

**Additional context**
![Capture d’écran (52)](https://github.com/user-attachments/assets/de18956f-66ce-491e-af8e-572bd5f78d07)
![Capture d’écran (53)](https://github.com/user-attachments/assets/dce209f4-6877-4d79-8c8c-eec6a38c633b)
![Capture d’écran (54)](https://github.com/user-attachments/assets/e6b3d67b-96d9-40f0-ac76-45aec608c0d4)

Translation :
Supprimer (la pièce jointe) : Delete the attached file
Ouvrir : Open
Enregistrer : Save

**Comment by bkaankose** [comment]
This is implemented with the version went live yesterday **v1.9.40**.

![image](https://github.com/user-attachments/assets/68d86721-fa16-4e95-a33d-77ca847a92d7)

Closing as fixed.
