### ISSUE TITLE
[Suggestion] Setting to enable/disable the focused inbox

### ISSUE THREAD

**Issue by Rakosmanjr** [bkaankose/Wino-Mail#46]
I'd really like to have an option to disable the "Focused" and "Other" tabs for the Inbox like the Mail app has. I've always found it hard to keep track of emails when they get split like that.

This is the setting in the Mail app:
![image](https://github.com/bkaankose/Wino-Mail/assets/917032/04c7fd56-75bf-4286-af6e-2c2d657ccbd2)

And the same setting in the new outlook app:
![image](https://github.com/bkaankose/Wino-Mail/assets/917032/31f3017f-2734-40ba-83a0-63ebad9c6546)

Behavior (from the outside perspective at least) would then be fairly straight forward:

* When the user opens Settings
    * The sub-setting "Focused Inbox" would be present in the given list of sub-settings

* When the user opens the "Focused Inbox" sub-setting
    * An option to enable and disable the focused inbox is visible

* When the user selects the option to sort emails into "Focused" and "Other"
    * The two tabs "Focused" and "Other" are visible at the top of the Inbox
    * Selecting either tab switches between the two views of the Inbox
    * Emails in the Inbox are displayed only in their corresponding tab

* When the user selects the option to _not_ sort emails into "Focused" and "Other"
    * No tabs are displayed at the top of the Inbox
    * The text "Inbox" is displayed at the top of the Inbox
    * All emails in the Inbox are displayed together in a single list

**Comment by bkaankose** [comment]
@Rakosmanjr could you please confirm if this is the setting you were looking for?
