### ISSUE TITLE
[Bug] Crash when renaming folder of Outlook account

### ISSUE THREAD

**Issue by blablabla123455** [bkaankose/Wino-Mail#462]
Wino crashes when renaming folder. It happens for outlook account, I didn't check gmail or imap.

**Comment by blablabla123455** [comment]
In Wino Client logs: `[ERR] [Wino Crash] System.NotSupportedException: Specified method is not supported.`

**Comment by bkaankose** [comment]
There was an issue with deserialization of the UI message. This will be fixed with the next update. Thanks!

**Comment by bkaankose** [comment]
It should be fixed with the version 1.9.40 which went live yesterday. Closing the ticket as resolved. We can re-open if it's not working still.

Thanks!
