### ISSUE TITLE
Loophole: Multiple Linked Accounts should count as more than 1 free account used

### ISSUE THREAD

**Issue by bkaankose** [bkaankose/Wino-Mail#468]
### Discussed in https://github.com/bkaankose/Wino-Mail/discussions/467

<div type='discussions-op-text'>

<sup>Originally posted by **BenjaminWang236** November  5, 2024</sup>
TLDR: Title

Hello, thank you so much for this app. Currently switching to Wino Mail because MS Mail and Calendar kept re-installing "Outlook (new)" like a virus.

Anyways, I was setting up the Linked Accounts as I was adding each accounts, fully intending to upgrade to Unlimited Accounts midway through, when I noticed that linked account, which currently has 3 linked emails, counted as "1 out of 3 free accounts used". Seems like a loophole.

![ApplicationFrameHost_fI9S9OTgbf](https://github.com/user-attachments/assets/755f5fcd-01a5-4bd7-a1a4-7028c406a4fc)
</div>

**Comment by hellomadworld** [comment]
🤦

**Comment by bkaankose** [comment]
Version 1.9.40 has this fixed. Closing.
