### ISSUE TITLE
[Bug] InfoBadge in Folders list does not update after deleting an E-Mail

### ISSUE THREAD

**Issue by Pinguin2001** [bkaankose/Wino-Mail#47]
I had one draft in my Drafts folder, which the InfoBadge displayed properly.
After deleting the draft, the InfoBadge didn't disappear, even though there were no more drafts left.
After a restart of Wino, the InfoBadge disappeared.

Wino 1.6.6
Mail account type: Custom IMAP
Windows Build 25982.1000 AMD64

![WinoMail](https://github.com/bkaankose/Wino-Mail/assets/75797743/7596ae8c-ec47-4748-aabc-ce2f98751684)

**Comment by bkaankose** [comment]
This issue will be fixed with the new synchronization mechanism in the next release. Labeling as fixed for now.

Thanks.

**Comment by bkaankose** [comment]
Version 1.6.7 is released. Please @Pinguin2001 check this issue on the new version and close if possible.
