### ISSUE TITLE
[Bug] Windows Mobile - cant install from store

### ISSUE THREAD

**Issue by Trevor89** [bkaankose/Wino-Mail#476]
**Describe the bug**
I downloaded Wino on PC, then went to store and "Owned" but wino just has ... next to it (not install)

**Expected behavior**
"A windows Mail Client for All windows devices" - I expect to be able to run on Mobile too

**Screenshots**
nothing to show except the lack of "Install" button

**Additional context**
950XL with last update 1709(dec) (15254.603)

**Comment by bkaankose** [comment]
I don't think Wino can run on Windows Phone unfortunately. Underlying tech we use for the UI does not allow that.
