### ISSUE TITLE
[Bug] Grammar mistakes in UI

### ISSUE THREAD

**Issue by peldas** [bkaankose/Wino-Mail#477]
**Describe the bug**
Grammar mistake in mail notification, talks about "new mails" which is incorrect as "mail" is uncountable in English.  (Side note, the popup asking to rate in the Microsoft Store also makes the same mistake with "feedbacks" instead of "feedback").

**Expected behavior**
It should say either "new messages" or "new emails".

**Screenshots**
![image](https://github.com/user-attachments/assets/01c1832c-1e10-475b-ab6c-4f60b2b262fe)

**Comment by jstedfast** [comment]
I would probably recommend:

**New Mail**
You have 227 new messages.

**Comment by bkaankose** [comment]
Version 1.9.40 must have the new strings. Closing as fixed.
