### ISSUE TITLE
Cant connect work mail

### ISSUE THREAD

**Issue by LaShonkilla** [bkaankose/Wino-Mail#482]
When i try to connect my work mail I get this error 

"Connected to imaps://tempo.superhosting.rs:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS MOVE SNIPPET=FUZZY NAMESPACE LITERAL+ NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
W: Supported authentication mechanisms: PLAIN, LOGIN
C: A00000000 COMPRESS DEFLATE
S: A00000000 BAD Error in IMAP command received by server."

![image](https://github.com/user-attachments/assets/7467e618-c253-4d34-8a4e-1575ddaa80b0)

I tried everything every option tried different mails changed passwords tried ports without security I'm talking to my server host for a week and they don't seem to find anything wrong they tried to connect my mail to Thunderbird and it works, for now I'm using it but its ugly and to complicated i need something simple like dead Mail app was and what wino mail EXACTLY is.

Pls help i will love to use winomail.

**Comment by bkaankose** [comment]
Looks like COMPRESS command must be sent to IMAP server **after** the authentication, but Wino does it **before** authentication. I will change the order of issuing the commands. That should do the trick.

**Comment by LaShonkilla** [comment]
I dont know if you change it already but I get the same error 

"
Connected to imaps://tempo.superhosting.rs:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS MOVE SNIPPET=FUZZY NAMESPACE LITERAL+ NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
W: Supported authentication mechanisms: PLAIN, LOGIN
C: E00000000 COMPRESS DEFLATE
S: E00000000 BAD Error in IMAP command received by server.
"

**Comment by bkaankose** [comment]
The update  has not been pushed yet. I will let you know once it's released.

**Comment by LaShonkilla** [comment]
Thanks!

**Comment by bkaankose** [comment]
Update went live yesterday (1.9.40). Please give it a try and let me know. Closing as fixed for now.
