### ISSUE TITLE
Mail history missing

### ISSUE THREAD

**Issue by davidbordon** [bkaankose/Wino-Mail#489]
**Describe the bug**
While searching for old emails i could not fetch anything prior to SEP 1 2024.
The email account is an @hotmail.com, set up with the automatic microsoft 365 integration.

**Expected behavior**
I expected to find email from all the way back, when i created the email account. It only displays about 3 months of email.

Thanks to the developers, this app has been the only worthy successor of the Win mail app.

**Comment by bkaankose** [comment]
Thanks for giving Wino a try. This is related to Online Search functionality as well.

We are tracking the progress on this issue #34 
Closing as duplicate.
