### ISSUE TITLE
[Bug]I can't find a setting for the synchronization period

### ISSUE THREAD

**Issue by PeterHans-prog** [bkaankose/Wino-Mail#492]
The app has been great up until now but I can't access older emails. They're all there on my phone, but in Windows Mail I can't find the setting for no time limit and at the end of December it only shows me emails up to September of the same year. In Windows Mail it worked (1 month / 3 months / no limit) in the account settings I can't find the option to set something there, it seems to be set to 3 months. If anyone knows how to do it I would be grateful for information.

**Comment by bkaankose** [comment]
Thanks for giving Wino a try. This is related to Online Search functionality as well. It's still not implemented, but planned to be for the next version. I am doing some tests about this topic along with wino calendar development.

We are tracking the progress on this issue #34 
Closing as duplicate.
