### ISSUE TITLE
Allow setting the app as a default app for MAILTO protocol

### ISSUE THREAD

**Issue by Daveid105cz** [bkaankose/Wino-Mail#52]
As said in the title, would be nice if I could associate the app as a default for URL:MAILTO protocol so clicking mailto links opens the client and fills the address bar with the address

**Comment by bkaankose** [comment]
This is definitely something I want to include for the next release.

**Comment by akamienski** [comment]
Hello,

I've seen you added fixed label to this issue, yet I can't select winomail as default app for mailto. How is it actually done then?

**Comment by bkaankose** [comment]
> Hello,
> 
> I've seen you added fixed label to this issue, yet I can't select winomail as default app for mailto. How is it actually done then?

This is fixed in beta release.

https://github.com/bkaankose/Wino-Mail/releases/tag/beta

**Comment by bkaankose** [comment]
Closing as fixed.
