### ISSUE TITLE
"Synchronization in progress" popup is annoying when quickly checking for new e-mails

### ISSUE THREAD

**Issue by asuetin** [bkaankose/Wino-Mail#55]
The progress bar is a bit distracting as well. It also makes the left menu jump up when it finishes. 

Is there a way for synchronization to be done in the background and be invisible to the user?

**Comment by bkaankose** [comment]
**Smarter synchronization**: Full synchronization is deprecated. Now, Wino can determine which folders needs to be synced exactly after each operation, or not sync at all. This means every synchronization will take much much less than before going forward.

This will be released soon with the next version. Also, I removed the annoying popup for confirmation on closing the app for next version.

Progress bar topic is something to discuss when the UI revamp work is started for later versions. I don't think it's a priority at this moment.

**Comment by asuetin** [comment]
> This will be released soon with the next version. Also, I removed the annoying popup for confirmation on closing the app for next version.

That's great to hear.

> Progress bar topic is something to discuss when the UI revamp work is started for later versions. I don't think it's a priority at this moment.

I agree it's not a big issue, especially with the smarter synchronization.

**Comment by bkaankose** [comment]
I made sure the progress does not annoyingly modify the height of the menu item for the next version though, FYI.
