### ISSUE TITLE
Can't add school email

### ISSUE THREAD

**Issue by OzgurAkyali** [bkaankose/Wino-Mail#58]
He asks for permission because he cannot trust the application. Since it is a school email, I do not know how to get permission, how can I solve it?

**Comment by bkaankose** [comment]
Office365 accounts are not supported unless your administrator explicitly allows Wino Mail.

**Comment by clragon** [comment]
I also have this issue. The administrators of my university will not allow this app to be added.
However, from what I can tell, it is possible to access Outlook emails even without this permission being needed, as I have seen other Email clients do this.

Is there no planned support for that kind of sign up?
