### ISSUE TITLE
Title bar buttons are white when window is in focus (light theme)

### ISSUE THREAD

**Issue by elio44** [bkaankose/Wino-Mail#6]
The title bar buttons are white on the light theme and are hard to see when the window is in focus. They turn darker when the window is out of focus. I tried switching themes back and forth but couldn't get it fixed. Am running windows 11 22H2 build 22623.1325 beta channel
![title bar buttons](https://user-images.githubusercontent.com/113631536/220369048-8edbb32c-ca13-4430-a73a-e7563a123a46.png)
window is in focus
![title bar buttons out of focus](https://user-images.githubusercontent.com/113631536/220369341-8d6c9129-dbbe-4eac-bc24-8257edf1ab9d.png)
window is out of focus

**Comment by bkaankose** [comment]
This bug has been taken care of for the upcoming release **preview 1.2**
