### ISSUE TITLE
[Feature request] Unified inbox

### ISSUE THREAD

**Issue by SlowNicoFish** [bkaankose/Wino-Mail#60]
It would be really nice to have an "All inboxes"/"Unified inbox" view to show all inboxes from all added accounts.

**Comment by bkaankose** [comment]
This feature is in my backlog. Next release will have underlying system changes to support this, but not the feature itself.

I expect this feature to go-live in January.

**Comment by Drabenstein** [comment]
Hello, are there any updates on this one? :)

**Comment by bkaankose** [comment]
Unified/Linked/Merged inbox feature is available as v1.7.0. 

Closing as fixed.
