### ISSUE TITLE
Only "Personal" is available in Gmail categories

### ISSUE THREAD

**Issue by AkazaRenn** [bkaankose/Wino-Mail#66]
I saw they are synced in the account settings, but didn't find how I can access them. Can you please help me with that?
<img width="162" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/e6a336f4-8a2e-44a1-973e-916142a9a3b1">
 There's a category button in the side bar, but expanding it only shows one folder called "Personal":
<img width="164" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/d79e0cb7-0a5b-4bcb-97c1-184d87bc8bd1">

**Comment by bkaankose** [comment]
I couldn't find any issues with the latest version. Following screenshot is from last version:

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/8b1f495a-e181-480c-b09e-ede6e5522c46)

Can it be related to your Gmail settings somehow? Your account name and "Personal" folder in Gmail is not related as well, so it can't be that. Maybe in Gmail there's an option to disable these categories? I don't know, just thinking out loud...

**Comment by bkaankose** [comment]
Also, these categories are only enabled when you use API version of Gmail in Wino. IMAP setup will not recognize those.

**Comment by AkazaRenn** [comment]
@bkaankose Yes I'm using the API version of Gmail, here's what I get from sidebar:
<img width="164" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/d79e0cb7-0a5b-4bcb-97c1-184d87bc8bd1">
Not sure what I did wrong with it...

**Comment by AkazaRenn** [comment]
Here's an update that I can still only see "Personal" in 1.7.2.0:
![image](https://github.com/bkaankose/Wino-Mail/assets/8340896/548c0ae3-962a-4505-b302-8e6df202d104)
I'm thinking if it could be a problem of my Gmail account but absolutely not sure what I can do in that case...

**Comment by AkazaRenn** [comment]
But it can see all my categories in the configure systems folder dialog?
![image](https://github.com/bkaankose/Wino-Mail/assets/8340896/ba002334-89c6-412b-9403-60778dfc8ed6)

**Comment by bkaankose** [comment]
@AkazaRenn can it be that they are disabled from web portal? I don't think this is something I can detect from the logs, but looks like they are synced but marked as hidden in the API.

**Comment by AkazaRenn** [comment]
@bkaankose you are right, I just realized there's an option `Show in label list` in Gmail settings 🥲
