### ISSUE TITLE
IMAP bug

### ISSUE THREAD

**Issue by ImerNesimi** [bkaankose/Wino-Mail#67]
Can not configure IMAP. My IMAP is set up for StartTLS.

An error occurred while attempting to establish an SSL or TLS connection.
The host name(mail.******.com) did not match any of the names given in the server's SSL certificate:
*.setssl.com
  setssl.com

**Comment by 17blue17** [comment]
Similar issue I can not configure IMAP for yahoo and I have followed all the instruction on the web for setting up a yahoo imap account.  I get login invalid credentials when testing server connection.

**Comment by iiaannn** [comment]
me too, when i tried to configure my company email, it shows the same error, i am sure the configure is totally correct.

**Comment by bkaankose** [comment]
Version 1.6.12 have some improvements on IMAP setup dialog. Could you please re-test with this version?

**Comment by ImerNesimi** [comment]
Same error 
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/97f2a05d-037f-4f34-ab29-6476b0489ebf)

One more thing, everytime i start the app i get this message, can you make it to show only once.
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/6a0d9ca5-49b0-4965-bb67-af9f8e2be60b)

**Comment by ImerNesimi** [comment]
Still the same
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/6efb2a4e-a66c-4fa6-8314-99b1c64b2cce)

One more thing, everytime i start the app i get this message, i have background apps disabled, it would be better if it shows just one time and do not remind again button.
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/63d66064-fa62-4483-883e-96c7dbc66633)

**Comment by ImerNesimi** [comment]
Still the same
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/d8135f4b-762d-4bc4-95ea-7fb69a413e16)


One more thing, everytime i start the app i get this message, i have background apps disabled, it would be better if it shows just one time and do not remind again button.
![image](https://github.com/bkaankose/Wino-Mail/assets/123909496/63d66064-fa62-4483-883e-96c7dbc66633)

**Comment by bkaankose** [comment]
This issue should be fixed in the latest version 1.9.0. Please re-open if you still experience it. Background execution is also removed from the app.
