### ISSUE TITLE
Localization and Contribution Guide

### ISSUE THREAD

**Issue by bkaankose** [bkaankose/Wino-Mail#7]
All strings in Wino should be localized for multiple languages. Right it only has English as default language, and there is no localization support under the hood.

Wino must support as much as languages possible for better experience. There should be also contribution guide for those who want to provide translation files.

**Comment by Kvasenok** [comment]
I think CrowdIn is good enough, but I guess it depends on the app's localization support in general. It should be incorporated first. I hope there is progress on this part.

**Comment by bkaankose** [comment]
Localization support is implemented for the big version I'm working on which will be released in February (**1.7.0**)

I have created a Crowdin page for people to contribute. Right now, I don't have translators that own the language and it's open to everybody.

All translations will be included in 1.7.0 at the time of release. Please refer to [Wino Crowding Page](https://crowdin.com/project/wino-mail) if you'd like to bring Wino into different languages.

**Comment by bkaankose** [comment]
Closing this issue as the underlying needs for translations (Crowdin page and localization support in the app) are completed.

**Comment by Kvasenok** [comment]
Hi @bkaankose 
I just wanted to notify you that your CrowdIn project is currently suspended which makes it impossible to contribute new translations.

**Comment by bkaankose** [comment]
> Hi @bkaankose I just wanted to notify you that your CrowdIn project is currently suspended which makes it impossible to contribute new translations.

Could you please retry?

**Comment by realgooseman** [comment]
I can confirm, it works fine now.

**Comment by Kvasenok** [comment]
@bkaankose now everything's fine
