### ISSUE TITLE
Client sometimes fails to launch

### ISSUE THREAD

**Issue by Rokeugon** [bkaankose/Wino-Mail#71]
Sometimes when i go to open the client it will open the window and then immediately close within a split second giving me the indication it just crashed or something. 

i then need to go back into start and reopen it which it will then fully load. not sure if its something to do with the idle process or if its just actually crashing when trying to re-open but yeah minor annoyance!

**Comment by MarcAnt01** [comment]
I stopped getting crashes with the latest version (1.6.11)

**Comment by bkaankose** [comment]
@Rokeugon v1.6.11 had improved launch activation. Do you still have this issue?
