### ISSUE TITLE
Feature request: option to set a quick action that appears on hover for an email

### ISSUE THREAD

**Issue by Benjin** [bkaankose/Wino-Mail#72]
I like Outlook.com/new mail app's implementation the best, where it takes up the full height of the email preview for maximum click target.

Pri 1: ability to configure the action (archive, delete, mark as read, flag/star, etc.)
Pri 2: option to automatically mark emails as read when archiving
Pri 3: ability to configure up to 3 actions for availability on hover, e.g.

![image](https://github.com/bkaankose/Wino-Mail/assets/1609827/9f1973df-09b5-4a65-968b-49d9fa8bf305)

----

Wino Mail right now:
![image](https://github.com/bkaankose/Wino-Mail/assets/1609827/607de244-8805-4ad1-98f8-edab38c93ff8)

Windows Mail example:
![image](https://github.com/bkaankose/Wino-Mail/assets/1609827/7a126316-a37a-444f-a066-69bd5d711e48)

Outlook.com/new Mail app example:
![image](https://github.com/bkaankose/Wino-Mail/assets/1609827/b9565cfe-1039-464f-82c5-cccd5dfbaaf8)

**Comment by bkaankose** [comment]
Hover actions are implemented in version 1.6.11. They are adjustable from settings as well. The design looks very similar to Windows Mail right now. More advanced UI options will be implemented later on the big UI revamp.

The other item you mentioned in number 2 is something I think of bigger, like policies, which I will not be implemented in the near feature since Windows Mail doesn't have it.

We can start thinking about doing that big UI revamp and policies once the app overcomes the core issues and catch up with the skills that Windows Mail has as of today.

Please give the hover actions a try and let me know if it exceeds the quality gate for you as it is.

**Comment by Benjin** [comment]
Thanks for adding them so quickly!

A couple pieces of feedback:

* There's no option to have fewer than three actions.  In my case, I only care about having Archive as a quick action, and would rather have a bigger click target than two extra buttons that I don't need.  Fix: allow for selecting `(none)` as an option, and make the remaining button(s) (if any) take up more width.
* I can set all three buttons to Archive, and all three still show up.  Fix: disallow setting the same action for multiple buttons
* No hover indicator or tooltip.  This is important for knowing whether my mouse is actually on the intended clickable element.  I'd also recommend adding colors to the actions so that they're easier to pick out the correct one immediately.  Other apps and UIs, I see green for archive, red for delete, blue for mark as read/unread...
* I _strongly_ prefer Outlook.com's UX for quick action buttons over Windows Mail's (see screenshots from original issue).  The advantage of having a full-height button is that it's far easier to quickly triage multiple emails by clicking down the list - I can land anywhere in the Y-axis and only have to be accurate along the X-axis.  With the old Windows Mail app (and with Wino Mail), I need to be accurate along both axes, which is far more difficult from a usability standpoint due to Fitt's Law of UI design.
  * I realize this takes up some message preview space.  To me, I'd much rather have an easier-to-click button than an extra character or three of preview.  But maybe this is a good opportunity to make the width of the preview pane adjustable via dragging?

**Comment by bkaankose** [comment]
There are some improvements done to conversation threads with today's release 1.9.0 which should cover all the issues you mentioned above.

Closing this issue.
