### ISSUE TITLE
IMAP:  Syntax error in CAPABILITIES, Unexpected token '+'

### ISSUE THREAD

**Issue by gslance** [bkaankose/Wino-Mail#75]
Trying to add a custom IMAP mailbox, but its preventing me by showing this problem. 

![Schermafbeelding 2023-12-12 184059](https://github.com/bkaankose/Wino-Mail/assets/6259697/e340d370-0aa9-4321-9cc5-be3378934399)

**Comment by bkaankose** [comment]
I think it's the same issue [with this one](https://github.com/jstedfast/MailKit/issues/1654)

Wino use MailKit v4.2.0 but looks like fix is pushed for v4.2.0.837 of MailKit. I will update it for the next version.

**Comment by gslance** [comment]
Confirmed fixed in app version 1.6.12, thank you.
