### ISSUE TITLE
Unexpected focus when creating a new mail

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#76]
The focus should be set to the addressee rather than on the mail content. This is the behavior of any Desktop mail app

**Comment by bkaankose** [comment]
1.6.12 should have this fixed. Could you confirm? @MarcAnt01

**Comment by MarcAnt01** [comment]
It's NOT fixed. I can see visually that it goes in the proper field for some instants, before going to the body of the e-mail

**Comment by bkaankose** [comment]
Yeap just realized that... Sorry, will push another fix in 2 days.

**Comment by bkaankose** [comment]
This issue should be fixed in the latest version 1.9.0. Please re-open if you still experience it.
