### ISSUE TITLE
Different ux to disable the signature

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#77]
I'm not a fan of signatures, I know it can be overcome by setting an empty signature, but I think it's a good idea to offer an explicit option like Windows Mail app

**Comment by bkaankose** [comment]
You can disable signature in this page

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/2201bf5d-f039-4746-8701-12662bbc009f)

"Enable Signature" is a toggle button. Once toggled and saved you won't get any default signature for that account. The UX on this is pretty bad though.

**Comment by MarcAnt01** [comment]
Ah I didn't see it, but let me tell this is a terrible ux. A button is thought for performing an action, not for stuff that has to be enabled/disabled. Toggleboxes and checkboxes exist for this reason.

**Comment by bkaankose** [comment]
I have an interesting story about why it had a terrible UX and the headlines go back to

- Implementation of account signatures.
- Not having a db migration system at a time.
- **ToggleSwitch** IsOn being bool instead **ToggleButton** IsToggled being **bool?**
- Me being lazy.

It's expected when you ship this fast :) Let's keep this issue open with UI label to improve this UX later on.

**Comment by bkaankose** [comment]
Version 1.7.2 is released today to Microsoft Store. Closing the issue since it's already fixed in the release. This is how it will look now under account settings

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/03bf2ebf-798e-4365-9793-6fa4fc88d8b5)
