### ISSUE TITLE
Discord linking does not work in-app nor on the website

### ISSUE THREAD

**Issue by gslance** [bkaankose/Wino-Mail#79]
The link to the Discord in the app will disable several buttons but never actually redirect to discord. 

![Schermafbeelding 2023-12-13 193542](https://github.com/bkaankose/Wino-Mail/assets/6259697/10e2acea-97e1-480a-9489-545b47644768)

In addition, the Discord link [on the website](https://www.winomail.app/) links to a non-existant channel URL. This should be the server URL. 

PS: it's not really called a "Discord Channel", since a channel is just one of several channels that make up a server. You're supposed to have an invite link created for joining the server. Consult your Discord server settings.

**Comment by bkaankose** [comment]
Thank you for the report.

Recent changes about dialog service caused this issue. Normally you should see this popup after clicking that button.
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/2bd33040-de4a-41f8-a1f0-232699ba1b31)

I'll include a fix in the next release.

**Comment by bkaankose** [comment]
@gslance This should also be fixed in 1.6.12. Can you confirm if you are able to see the message and go to server? I have updated the link on the website as well.

**Comment by bkaankose** [comment]
Closing the issue since it's resolved now.
