### ISSUE TITLE
Gmail is broken

### ISSUE THREAD

**Issue by foursplaysroblox** [bkaankose/Wino-Mail#8]
Hey devs I just installed the Microsoft version of Wino Mail but the gmail is not working can any dev help?

https://user-images.githubusercontent.com/82078139/221855102-ebc7cb1c-37a3-4485-ad52-e91cd903d794.mp4

**Comment by bkaankose** [comment]
Gmail integration is still in progress and will be available for the next release. Right now only Outlook provider is available.

**Comment by foursplaysroblox** [comment]
Thanks

**Comment by senolfndk** [comment]
same problem gmail not connecting
![Ekran görüntüsü 2023-03-23 133442](https://user-images.githubusercontent.com/52818836/227178368-bac09100-cf45-4a95-b602-f18ade5eaa50.png)
![Ekran görüntüsü 2023-03-23 133849](https://user-images.githubusercontent.com/52818836/227178372-65307f18-42a8-4cf0-886a-31562c27c1d1.png)

**Comment by senolfndk** [comment]
I removed the other account, gmail is not loading again
![Ekran görüntüsü 2023-03-23 134328](https://user-images.githubusercontent.com/52818836/227179519-db29e885-5f28-45a9-80f3-c20f357d60ea.png)

**Comment by senolfndk** [comment]
okay, done

**Comment by foursplaysroblox** [comment]
Thanks for fixing it I have been waiting for a long time

**Comment by ItzPeto** [comment]
Seems like the situation has gotten worse, now I don't even have any buttons to click or anything.
![image](https://github.com/bkaankose/Wino-Mail/assets/46417703/94b1d07b-56b6-4e97-bdaf-27475ab37b47)

**Comment by sameerasw** [comment]
> Seems like the situation has gotten worse, now I don't even have any buttons to click or anything. ![image](https://user-images.githubusercontent.com/46417703/244875674-94b1d07b-56b6-4e97-bdaf-27475ab37b47.png)

![image](https://github.com/bkaankose/Wino-Mail/assets/68902530/28fe161d-040d-4bb9-bdbc-5415a409726d)


yeah , same... Because Google removed the ability to allow unsafe apps to be logged in. Even without 2FA.

**Comment by bkaankose** [comment]
Thanks all for the reports! I wasn't aware of the situation. Reopening the issue.

Looks like new Google policies blocked Wino for authentication. 'Preview' tag in the name is the problem for Google. I will remove the 'preview' tag from the name, be compliant with Google policies and publish a new version soon. Unfortunately right now there is no way to authenticate Gmail accounts in this version.

**Comment by 14142000** [comment]
The latest update got slightly farther but now I have this error 
![image](https://github.com/bkaankose/Wino-Mail/assets/3375830/8cb93300-5466-464f-a8ea-07a6d7bc08f0)

**Comment by 14142000** [comment]
> The latest update got slightly farther but now I have this error ![image](https://user-images.githubusercontent.com/3375830/252056123-8cb93300-5466-464f-a8ea-07a6d7bc08f0.png)

detailed error for dev:

Error 403: access_denied
Request details: response_type=code redirect_uri=google.pw.oauth2:/oauth2redirect state=xJNLkt4tMB3vrC76zgnFL7D-tVVIGVnyCzYAvLs3kTQ code_challenge_method=S256 client_id=973025879644-s7b4ur9p3rlgop6a22u7iuptdc0brnrn.apps.googleusercontent.com code_challenge=SN1kzUf9UDbg2zaVTIZkU0bvtZ4Nu7-8XXq0Ev0Ku24 access_type=offline scope=https://mail.google.com/

[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/production-readiness/brand-verification?hl=en#projects-used-in-dev-test-stage)

**Comment by diskscape** [comment]
I'm still getting the error that @ItzPeto got. 

https://github.com/bkaankose/Wino-Mail/assets/39781374/52dfaa64-864a-464f-b948-5170dace3c14

I'm hoping this can get fixed soon. I really would love to use Wino mail as my default mail app, since Microsoft is trying to replace their default with the clunky new Outlook app.

**Comment by ItzPeto** [comment]
Can this issue get a higher priority? The app is basically unusable for us Googletards and it's been like this almost 2 months.

**Comment by bkaankose** [comment]
> Can this issue get a higher priority? The app is basically unusable for us Googletards and it's been like this almost 2 months.

It's the highest priority :) Yesterday I completed a CASA Tier 2 process for it. It takes couple business days for Google and other external teams to review the policy/app changes. There is nothing I can do to make it faster unfortunately. We just need to wait and hope for the best.

**Comment by bkaankose** [comment]
Finally, we got the final approval from Google :)

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/5687032a-d20d-4097-ab37-c0a9d9b7f782)

I tested with different accounts and everything seems to be working with Gmail. You should be able to login and use Wino for Gmail accounts.

Closing this issue. If you experience any other issue using Gmail for non-authentication topics, please open a new issue.

**Comment by chrizbee** [comment]
@bkaankose I have no clue if this is related or not, but I still can't login with my Google account.

![brave_lkt8481rT5](https://github.com/bkaankose/Wino-Mail/assets/35270845/79e09a04-b57b-4194-a4f5-76da2aa86804)

This means: "An error has occurred. A problem occured. Please try again."

After that Wino is stuck on "Account information is being saved."

![ApplicationFrameHost_SGhWVhwJcY](https://github.com/bkaankose/Wino-Mail/assets/35270845/3400580c-2c21-4ce7-b9ad-029885aaf2eb)

**Comment by chrizbee** [comment]
For anyone having the same problem:
I switched from Brave to Edge as my default browser and tried again - this time it worked flawlessly.
