### ISSUE TITLE
Cant add account.

### ISSUE THREAD

**Issue by i2sage** [bkaankose/Wino-Mail#81]
https://github.com/bkaankose/Wino-Mail/assets/137275372/4a3d44b2-b8a8-496f-99e3-826b706b69fc

can't add account. I tried reinstalling webview,edge and multiple reinstalls but still the same issue.
windows 10 22h2.

**Comment by bkaankose** [comment]
I have released a new version **1.6.12** to address this issue. Which version you have in this recording?

**Comment by i2sage** [comment]
> I have released a new version **1.6.12** to address this issue. Which version you have in this recording?

i have installed it through winget as well as ms store. i upgraded to windows 11 and just out of curosity i installed it again and it works on 11.

**Comment by bkaankose** [comment]
Can we close this issue since it's resolved in **1.6.12**?

**Comment by i2sage** [comment]
my bad
