### ISSUE TITLE
version 1.6.12 Crash on clicking new mail

### ISSUE THREAD

**Issue by 17blue17** [bkaankose/Wino-Mail#83]
I updated using the Microsoft store to 1.6.12.   The new version crashes if I click on new mail.  This happens every time so is a repeatable crash.  It also crashed one other time doing something else - I don't remember what - maybe manage account or click on inbox.  Sorry.   Also when in manage accounts how does one exit manage accounts?  I can close manage accounts if I click on say an inbox.  It would be nice to have a close button to leave manage accounts.

**Comment by 17blue17** [comment]
[WinoDiagnostics.log](https://github.com/bkaankose/Wino-Mail/files/13677402/WinoDiagnostics.log)
Not sure if this log will help or not.   I noticed that earlier when clicking new mail it would crash immediately.  Now when clicking new mail my three email accounts come up and then it crashes.  All three email are receiving mail correctly.

**Comment by Tiktack** [comment]
Wino mail improved a lot since 1.6.12. Current version is 1.9.2 and it shouldn't have crash after click on "new mail". Closing as fixed. Please re-open if you still encounter this problem.
