### ISSUE TITLE
[Suggestion] HTML email signature

### ISSUE THREAD

**Issue by simkoG** [bkaankose/Wino-Mail#86]
In our workplace, we have a mandatory email signature format that we are required to use. Currently, Wino Mail only allows the addition of simple text with some styling as the email signature. I was wondering if there could be an enhancement to support a more robust and customizable email signature, allowing for compliance with our organization's guidelines.

**Comment by Xavi3RElvis** [comment]
Wondering if the saved signature is possible to be reused from outlook web

**Comment by bkaankose** [comment]
> Wondering if the saved signature is possible to be reused from outlook web

https://learn.microsoft.com/en-us/answers/questions/1315401/get-email-signature-saved-to-an-outlook-account-vi

I don't think that is possible for now.

**Comment by EzraWard** [comment]
I also agree that this is a worthwhile enhancement. This is one of the few things holding me back from using Wino almost exclusively.

**Comment by bkaankose** [comment]
1.7.6 is released today that supports pasting HTML signatures directly into editor. Closing the issue for now, please re-open if you think it's not fixed :)

**Comment by simkoG** [comment]
Dear @bkaankose , did something happened with HTML signatures in the new version? On the previous release version I coud add custom HTML code as my signature. In the new version only the text gets inserted into the "Signature Editor" field and not the actual html. 

https://github.com/user-attachments/assets/6eef089e-0093-4314-8ea7-2d2760a55cee

**Comment by bkaankose** [comment]
> Dear [@bkaankose](https://github.com/bkaankose) , did something happened with HTML signatures in the new version? On the previous release version I coud add custom HTML code as my signature. In the new version only the text gets inserted into the "Signature Editor" field and not the actual html.
> 
>  Video.Project.1.mp4

I'll make sure for signature editor pasting with options is enabled. It's disabled for composing messages but it makes sense for signatures.
