### ISSUE TITLE
Remove in-app purchases

### ISSUE THREAD

**Issue by mrkrabs206** [bkaankose/Wino-Mail#89]
I want you to remove in app purchases
So I can add a lot of my accounts.

It's TOO EXPENSIVE
![this is too expensive please remove](https://github.com/bkaankose/Wino-Mail/assets/110676833/fefc7311-6670-4eab-8da7-0afbdd6f7531)

**Comment by mrkrabs206** [comment]
> Instead of begging here, why don't you make an app by yourself then? This entire Mail app, trying to redo what the old Windows Mail UWP used to be, is being developed by a single person, and you can't just beg people to do everything for free. They need income to survive as well.

too hard bro

**Comment by bkaankose** [comment]
Pricing is something that I did not spend a good time to come up with fair plan for all regions in the world; and I agree, current price is too high for some countries. Even though I defend 'Value based salary' when it comes to working for corporates, end users should not be affected by this and it's okay to have location based pricing for the app.

I will apply fair pricing for some regions later on.

**Comment by mrkrabs206** [comment]
> Pricing is something that I did not spend a good time to come up with fair plan for all regions in the world; and I agree, current price is too high for some countries. Even though I defend 'Value based salary' when it comes to working for corporates, end users should not be affected by this and it's okay to have location based pricing for the app.
> 
> I will apply fair pricing for some regions later on.

At least $0.99.
