### ISSUE TITLE
Feature request: Send as/Alias support

### ISSUE THREAD

**Issue by tmprnc** [bkaankose/Wino-Mail#90]
Hello,
I know Wino Mail is probably more intended for personal than professional use, but I prefer using it because I already used the default Windows Mail client, and this changes very little to my habits. I have set it up so that an Outlook email address I use exclusively for work is aliased using ImprovMX to both receive mail sent to, and send mail as a contact@website.com email. (actually, I don't think ImprovMX was required in the send as process, I merely just had to click a link sent to the address to prove that I owned it).
It isn't a custom mail server with its own IMAP/SMTP settings. It is Outlook, but mails sent from a personal Outlook.com cosmetically appear as though they have been sent from my website's domain name.

I'm sure my request is hardly a priority, and I'm not sure how feasible it would be to add this feature to Wino, considering that Gmail and Outlook probably implement it differently — particularly the identity check — but it would be particularly useful to me as I wouldn't have to use Thunderbird whatsoever.

Thank you.

**Comment by bkaankose** [comment]
To understand the feature request since I don't use it, is this the feature you are talking about ?

@bel57 @tmprnc 
https://support.microsoft.com/en-us/office/add-or-remove-an-email-alias-in-outlook-com-459b1989-356d-40fa-a689-8f285b13f1f2

If so I will mark this as a feature request and see what I can do in the future.

**Comment by bel57** [comment]
Yes exactly! Thanks for considering it, with that feature I'd definitely make the switch and ditch Outlook.

**Comment by tmprnc** [comment]
That is indeed the feature in question. Thank you.

**Comment by Xavi3RElvis** [comment]
This and category tags showing on emails would make me and many outlook 365 users switch to wino completely.
When paying for 365 you can create mail aliases and send mails using whatever you prefer even in the old mail app:
![image](https://github.com/bkaankose/Wino-Mail/assets/16775752/38392c82-6bc3-4fdb-b091-b3942f58291e)
that is especially useful mainly for professional accounts used for different tasks
not sure how easy it can be to implement though

**Comment by zanderp25** [comment]
I have aliases too, except through my iCloud email.

**Comment by edge261** [comment]
I noticed I need this feature more than I expected. Hope it's not too difficult to implement.

**Comment by bkaankose** [comment]
I did some analysis on the subject. Here's the summary:

**Outlook**
Wino Mail use MS Graph API to interact with Outlook messages. Looks like Graph API does not expose e-mail aliases for personal accounts (MSA). Only for AAD (Azure Active Directory). Retrieving aliases are only available via Outlook API which was set to be deprecated by Microsoft in favor of Graph API.

This means that there is no way right now for Wino to get your available e-mail aliases. 

**Gmail**
It's pretty straightforward. No blockers.

**IMAP**
IMAP servers don't have this concept. Everything is handled manually in the client.

If you have defined an alias for your Outlook or Gmail account, you must receive mails without an issue. Any mails sent to your alias will be received in your primary account's Inbox. This is handled by the mail provider and Wino does not do anything special there.

For sending, Wino needs to get aliases that your server can process. Above analysis shows that it's only possible for Gmail right now. However, for Outlook and IMAP, if you manually define the aliases you have then it's possible. Server would accept the Mime that Wino crafted in Wino and process as it is sent with one of your allowed aliases. I'm not sure how this works with SMTP though. 

This work requires a little bit more trial. I will see what I can do for the next upcoming days.

**Comment by ntpeters** [comment]
Thanks for looking into this! I'll be happy to be a tester for the feature once it reaches that point 🙂

**Comment by bkaankose** [comment]
v1.9.0 that addressed this issue is released to the Store. Closing as fixed.

**Comment by nebula-it** [comment]
Hey @bkaankose 
I was looking into this and for personal email the alias can be retrieved using `https://graph.microsoft.com/beta/me/profile/emails?$select=address` 
Any chance you can add the auto sync for Outlook using this?
Let me know if I should open a new issue for this.

**Comment by bkaankose** [comment]
> Hey [@bkaankose](https://github.com/bkaankose) I was looking into this and for personal email the alias can be retrieved using `https://graph.microsoft.com/beta/me/profile/emails?$select=address` Any chance you can add the auto sync for Outlook using this? Let me know if I should open a new issue for this.

Wino Mail does not use the beta graph api for now. Partially using it may require some changes which is not worth to bringing it at this point I think. Thanks for the heads up though, I will think about it in the future!

**Comment by nebula-it** [comment]
Totally understandable. Hoepfully it gets out of beta soon.

Thank you for the great work BTW ❤
