### ISSUE TITLE
[Win11 Desktop] Crashes whenever it receives a new mail.

### ISSUE THREAD

**Issue by ionpot** [bkaankose/Wino-Mail#92]
Hello, new user here.

I have a fresh install of Wino Mail v1.6.12.0 from MS Store on my Windows 11 desktop PC.

I only registered one personal Gmail account.

Whenever there is new mail, it seems to crash.

When I re-open, I can see the new mail in the inbox. And, I can open and read it without any problems.

It only crashes when receiving new email.

I've enabled logs, and attached the latest copy I got after the crash:
[WinoDiagnostics.log](https://github.com/bkaankose/Wino-Mail/files/13820836/WinoDiagnostics.log)

IMAP protocol logs have nothing.

**Comment by RSM9** [comment]
Same issue for me (and same version from MS Store). - using a normal Outlook account.

**Comment by bkaankose** [comment]
This issue should be fixed in the latest version 1.9.0. Please re-open if you still experience it.
