### ISSUE TITLE
iCloud Mail integration?

### ISSUE THREAD

**Issue by HideOnFluff** [bkaankose/Wino-Mail#96]
OMG Finally a proper minimal and system-integrated mail client! I love it so much!!! 

Are you planning on adding iCloud Mail anytime soon? I'm currently stuck on Apple's ecosystem and I would extremely appreciate it

I can't stress enough how beautiful your app is, amazing work! <3

**Comment by bkaankose** [comment]
Thank you.

iCloud is already integrated via IMAP. You can follow [this link](https://support.apple.com/en-us/102525) to make your iCloud Mail work with Wino.

Please close the issue if it works for you.

**Comment by HideOnFluff** [comment]
It worked! thank you so much.

**Comment by mrleblanc101** [comment]
@bkaankose Why not surface it as a top level option on the onboarding ?
Why only gmail and outlook ?

**Comment by mrleblanc101** [comment]
I've opened a seperate issue: #323
