### ISSUE TITLE
Crash on ARM Platform

### ISSUE THREAD

**Issue by SituChengxiang** [bkaankose/Wino-Mail#97]
The application crashed when I was tring to reply, and there seemed to have problems loading the content of the mail.
CPU: Qualcomm 8cx 2
OS: Windows 11 22635.2921
Version of Wino-Mail: 1.6.12.0

I will upload log few hours later.

**Comment by Viruslav** [comment]
That's probably because it uses an Arm32 version there. We need an Arm64 version.

**Comment by talynone** [comment]
Works just fine on my ARM64 Elite laptop. Installed from Windows Store which install the x64 version. Works fine in emulation, don't notice any slowness.

**Comment by Tiktack** [comment]
Arm64 works fine for a few versions. Tested with MS Surface 7 ( X Elite) native build. Closing as completed.
