### ISSUE TITLE
Bug: Sending via IMAP does not create a copy inside the "Sent" Folder

### ISSUE THREAD

**Issue by BBoehm** [bkaankose/Wino-Mail#98]
Sending an Email via IMAP does not seem to create a copy inside the "Sent" Folder.

Regardless of the reciepient, when using IMAP my sent mails don't appear in the according folder. This seems to be unrelated to the actual sending process of the email; at least in 1 case I was able to verify, that the Email has been received, even though it still does not appear in the "Sent" Folder.

Also it does not seem to be just a display bug, instead there really is no Mail in the sent folder, even if I access the according Mail account with other programs.

Used Version: 1.6.12.0

**Comment by bkaankose** [comment]
This is how your mail server behaves. Wino is just a communicator in the middle. If your mail server is configured to not create a copy of drafts after sending to the Sent folder, it will not create.

Which mail provider did you experience this? If this is a common thing that mail clients do in IMAP jargon maybe I can add support for it.

**Comment by LaVidaDura** [comment]
same as BBoehm here: sending via IMAP: sent mail is nowhere. If I look in the folder on GMX via web interface, I can not find the sent e-mail. However, the mail is received by the other party as it should.
IMAP Settings: mail.gmx.net Port 465

**Comment by bkaankose** [comment]
I am marking this as a bug because looks like this is sometimes a mandatory action to take in IMAP world.

For all IMAP accounts, Wino will check if the sent mail is already placed in Sent folder or not after sending. If not, then it'll automatically add the copy. If it's already in Sent, then no action is taken.

You'll be able to change this behavior in settings per-account.

**Comment by neurekadev** [comment]
I'm having this same issue. I cannot reliably use Wino Mail until this is resolved.

**Comment by bkaankose** [comment]
> I'm having this same issue. I cannot reliably use Wino Mail until this is resolved.

There is an option in the account settings to create a copy of the drafts in sent folder. Go to Manage Accounts and enable that setting.

Closing as fixed.

**Comment by neurekadev** [comment]
> > I'm having this same issue. I cannot reliably use Wino Mail until this is resolved.
> 
> There is an option in the account settings to create a copy of the drafts in sent folder. Go to Manage Accounts and enable that setting.

Why isn't this the default?
